### ISSUE TITLE
Issue while decoding JWT

### ISSUE THREAD

**Issue by amolchakane** [firebase/php-jwt#100]
I was trying to decode the generated token using decode function of https://github.com/firebase/php-jwt library.

Here is my code. I have defined private key in my configuration file using following line.
`define("FIREBASE_PRIVATE_KEY","-----BEGIN PRIVATE KEY-----\nMY_VERY_VERY_LONG_KEY\n-----END PRIVATE KEY-----\n");`

Here is the code to decode token.
`JWT::decode($token, FIREBASE_PRIVATE_KEY, array('RS256'));`

This code throws following exception.
`openssl_verify(): supplied key param cannot be coerced into a public key`

Can anyone suggest a solution to this?

**Comment by EralpB** [comment]
I'm having the exact same issue :/

**Comment by Shkeats** [comment]
@amolchakane @EralpB  With RS256 you encode using the _private_ key but you decode using the **public** part of the key. This way you can share the public key with other applications or services that may want to verify that the token was issued by your application without giving them the private key which would allow them to issue their own valid tokens.

```
$encoded = \Firebase\JWT\JWT::encode($decoded,(file_get_contents(storage_path().'/oauth-private.key')),'RS256',null,[]);

   $decoded = \Firebase\JWT\JWT::decode($reEncoded,file_get_contents(storage_path().'/oauth-public.key'),['RS256']);

```

**Comment by amolchakane** [comment]
@Shkeats Yes, you are correct. I used following code, and it works perfectly fine.
```
define("FIREBASE_PRIVATE_KEY","-----BEGIN PRIVATE KEY-----\nMY_VERY_VERY_LONG_KEY\n-----END PRIVATE KEY-----\n");
$pub_key = openssl_pkey_get_private(FIREBASE_PRIVATE_KEY);
$keyData = openssl_pkey_get_details($pub_key); 
return JWT::decode($token, $keyData['key'], array('RS256'));
```

**Comment by Shkeats** [comment]
@amolchakane OK glad it worked. You should close this issue now.
