### ISSUE TITLE
OpenSSL unable to sign data while generating custom token firebase V3 with php-jwt

### ISSUE THREAD

**Issue by parthjdabhi** [firebase/php-jwt#105]
Warning: openssl_sign(): supplied key param cannot be coerced into a private key in /home/unitefi2/public_html/phpjwt/src/JWT.php on line 196

Fatal error: Uncaught exception 'DomainException' with message 'OpenSSL unable to sign data' in /home/unitefi2/public_html/phpjwt/src/JWT.php:198 Stack trace: #0 /home/unitefi2/public_html/phpjwt/src/JWT.php(167): Firebase\JWT\JWT::sign('eyJ0eXAiOiJKV1Q...', NULL, 'RS256') #1 /home/unitefi2/public_html/phpjwt/test/test.php(27): Firebase\JWT\JWT::encode(Array, NULL, 'RS256') #2 /home/unitefi2/public_html/phpjwt/test/test.php(38): create_custom_token('8yzfPkGWlifpe0k...') #3 {main} thrown in /home/unitefi2/public_html/phpjwt/src/JWT.php on line 198

**Comment by JitenBhanushali** [comment]
I'm getting the same issue
Were you able to solve it?

**Comment by bshaffer** [comment]
This is an issue with the keys themselves, and their verification in `openssl`. Closing as there is nothing actionable in this library.
