### ISSUE TITLE
Exception thrown when setting expired time for the token

### ISSUE THREAD

**Issue by duyluandethuong** [firebase/php-jwt#106]
This is my code block

```
$issueTime = time();
$notBeforeTime = $issueTime + 10;
$expireTime = $notBeforeTime + 7200;

$token = array(
        "iss" => "http://example.org",
        "aud" => "http://example.com",
        "iat" => $issueTime,
        "nbf" => $issueTime,
        "data" => [
            "userID" => "1213",
            "username" => $username
        ]
    );
```

Whenever I set the "**exp**" time for the token, the following error was thrown.

> <br />
> <b>Fatal error</b>:  Uncaught exception 'Firebase\JWT\ExpiredException' with message 'Expired token' in /var/www/html/jwt/vendor/firebase/php-jwt/src/JWT.php:131
> Stack trace:
> # 0 /var/www/html/jwt/auth.php(40): Firebase\JWT\JWT::decode('eyJ0eXAiOiJKV1Q...', 'fy8ewrfi867buyu...',

If I keep the $token array as above, everything works fine.

Do you have any idea on this?

**Comment by katowulf** [comment]
Please include the timestamp you're setting expires to, as well as version info and a [minimal, complete, repro](http://stackoverflow.com/help/mcve).

**Comment by sadiqumar18** [comment]
i think the error is clear. You need to put your jwt decode function in a try catch. which will enable you catch the ExpiredException

**Comment by yash30201** [comment]
Closing as this seems answered.
