### ISSUE TITLE
What exception to catch when running JWT::encode()

### ISSUE THREAD

**Issue by kiwo12345** [firebase/php-jwt#111]
If I run JWT::encode() and it fails to create a token what error/exception is thrown?

Thanks,

**Comment by tuupola** [comment]
Looking at the source seems to thrown a [DomainException](http://php.net/manual/en/class.domainexception.php).

**Comment by bshaffer** [comment]
This is correct!

See [the documentation here](https://github.com/firebase/php-jwt/blob/main/src/JWT.php#L228)
