### ISSUE TITLE
Installing error with Composer

### ISSUE THREAD

**Issue by andrebruton** [firebase/php-jwt#112]
I get the following error when trying to install using Composer in a subfolder:

C:\xampp\htdocs\milk\jwt>composer require firebase/php-jwt
Using version ^4.0 for firebase/php-jwt
./composer.json has been updated
Root package 'firebase/php-jwt' cannot require itself in its composer.json
Did you accidentally name your root package after an external package?

Any idea how to fix this?

**Comment by berega** [comment]
try to run the composer for the directory (cd..)
C:\xampp\htdocs\milk>composer require ...

**Comment by bshaffer** [comment]
@andrebruton Yes, @berega is correct. Run the command `composer require firebase/php-jwt` from your application root directory, and not from the root directory of this repo.

```sh
# good
$ cd /path/to/my-project-dir && composer require firebase/php-jwt

# bad
$ git clone git@github.com:firebase/php-jwt.git && cd php-jwt && composer require firebase/php-jwt
```
