### ISSUE TITLE
Encode an array, get an object

### ISSUE THREAD

**Issue by stephen304** [firebase/php-jwt#12]
I put in an associative array:

```
$token = array(
    "id" => $user['id'],
    "username" => $user['username'],
    "email" => $user['email'],
    "realname" => $user['realname'],
    "expires" => time() + (24 * 60 * 60)
);
$token = JWT::encode($token, token_secret);
```

and when I decode, I get an object:

```
$profile = JWT::decode($token, token_secret);
print_r($profile);
```
## 

```
stdClass Object
(
    [id] => 1
    [username] => stephen
    [email] => email@me.com
    [realname] => stephen smith
    [expires] => 1404683315
)
```

Is this intentional? Right now I'm just casting it to array, but I think it would be good if it decoded to exactly what was put in?

**Comment by pravdinalex** [comment]
Аnd how should I get from paylod non standart fields, which names I should prepend with domain name? Shure need a param like that in json_decode...
