### ISSUE TITLE
unable to run project

### ISSUE THREAD

**Issue by ManishLSN** [firebase/php-jwt#122]
Hello All, 
I knew its silly question to raise here, but most of the cases i am not able run github projects on my localhost [Apache, mysql]. i usually download project as a zip and after extract i run cmd "composer install", and vendor directory and dependency installed, but what after that, i am not able to run project on local machine. 
any information ?

**Comment by psignoret** [comment]
Indeed, this is not the appropriate place for this question. You should ask this in a more general forum, such as StackOverflow. Don't forget to include precise details on exactly what your environment is, how it's configured, what you have attempted and what error messages you receive. Also include what you have already tried to do after you searched online for help. Always provide the steps for a [minimal, complete, verifiable example](http://stackoverflow.com/help/mcve).
