### ISSUE TITLE
JWT decode with RS256 algorithm

### ISSUE THREAD

**Issue by bobysf12** [firebase/php-jwt#123]
I'm trying to decode firebase auth and verify it to access my website, but i keep getting this error 

DomainException in JWT.php line 229:
OpenSSL unable to verify data: error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed

I'm using laravel btw but tymon\jwt is not helping with RS256. Please help

**Comment by TheFox** [comment]
Which `firebase/php-jwt` version to you use?

**Comment by tersmitten** [comment]
How did you generate the key pair?

We use this:

```sh
ssh-keygen -t rsa -b 4096 -f key;
openssl rsa -in key -pubout -outform PEM -out key.pub;
```

and that seems to work :-)
