### ISSUE TITLE
Invalid Custom TOken

### ISSUE THREAD

**Issue by kadircanerergun** [firebase/php-jwt#127]
Im using custom token auth on Firebase. I tried to generate token as the documentation said. But when i try to login in client side with (loginWithCustomToken(token)) method it gives an error below

```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "INVALID_CUSTOM_TOKEN"
   }
  ],
  "code": 400,
  "message": "INVALID_CUSTOM_TOKEN"
 }
}
```
I generate token with this code block as described in firebase documentation

```
$service_account_email = "USED_FROM_JSON_FILE"; //
$private_key = "USED_FROM_JSON_FILE";

function create_custom_token($uid, $is_premium_account) {
  global $service_account_email, $private_key;

  $now_seconds = time();
  $payload = array(
    "iss" => $service_account_email,
    "sub" => $service_account_email,
    "aud" => "https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit",
    "iat" => $now_seconds,
    "exp" => $now_seconds+(60*60),  // Maximum expiration time is one hour
    "uid" => $uid,
    "claims" => array(
      "premium_account" => $is_premium_account
    )
  );
  return JWT::encode($payload, $private_key, "RS256");
}
```

**Comment by saffabook** [comment]
Same issue +1

**Comment by bshaffer** [comment]
Hello! Thank you for filing this. 

I unfortunately cannot duplicate this issue. The above sample validated as expected. I would verify the following:

1. The service account email matches the private key
2. The project tied to the service account matches your firebase config (i.e. `authDomain`)
3. The token being passed to `loginWithCustomToken` is correct 

Unfortunately, the error message being returned from the API is not very helpful, so it could be any of these things or something else.

If you think there is a problem with the documentation, click **Send Feedback** in the top right corner of [the documentation page](https://firebase.google.com/docs/auth/admin/create-custom-tokens) and tell us the problem.

**Comment by JustDNA** [comment]
Same issue +1

**Comment by JustDNA** [comment]
I come across this error few times every day out of some 1000 times

**Comment by diamond-darrell** [comment]
I have a similar issue.
I found out that if I copy generated token from server response and just hardcode it in app (frontend side), it works fine. But if I pass received token, it fails.
So, I think that token is valid, but for some reason login fails.

**Comment by diamond-darrell** [comment]
I've figured out the problem in my case.
It was wrong time on the server. So, "iat" and "exp" dates were wrong

**Comment by delta9** [comment]
@diamond-darrell Thanks!! You saved me from pulling my hair out while testing.

**Comment by Rhonun** [comment]
@diamond-darrell THANK YOU!

**Comment by dyangua** [comment]
@theknicker the same problem i dont know, i use sdk firebase and works fine but with my custom jwt with parameters like documentation i have this `error Invalid assertion format. 3 dot separated segments required`

**Comment by rldaulton** [comment]
@dyangua did you find a solution to the error?
> i have this `error Invalid assertion format. 3 dot separated segments required`

**Comment by dyangua** [comment]
@rldaulton yes, i have this error because i try to create my custom token in node but in node you have method for that, in php works fine.

**Comment by dyangua** [comment]
`<?php
// Requires: composer require firebase/php-jwt
use \Firebase\JWT\JWT;

// Get your service account\'s email address and private key from the JSON key file
$service_account_email = "";
$private_key = "";

function create_custom_token($cedula, $is_premium_account) {
  global $service_account_email, $private_key;

  $now_seconds = time();
  $payload = array(
	"iss" => $service_account_email,
	"sub" => $service_account_email,
	"aud" => "https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit",
	"iat" => $now_seconds,
	"exp" => $now_seconds+(60*60),  // Maximum expiration time is one hour
	"uid" => $cedula,
	"claims" => array(
	  "premium_account" => $is_premium_account
	)
  );
  return JWT::encode($payload, $private_key);
}
?>`

**Comment by MrJellyB** [comment]
same error here,
when i tried to call signInWithCustomToken right after signInWithEmailAndPassword 
it worked fine, but when I was calling from other HTTP request it failed

**Comment by MrJellyB** [comment]
> @rldaulton yes, i have this error because i try to create my custom token in node but in node you have method for that, in php works fine.

can you elaborate?

**Comment by sharmam-lh** [comment]
Anyone has fixed "**Invalid assertion format. 3 dot separated segments required.**". I am facing same issues while using firbase "signInWithCustomToken(jti)" **jti** means **JWT ID token**

**Comment by madsongr** [comment]
Same error here. I've checked system time, changed uid from integer to string and decoded in jwt.io. In [jwt.io](https://jwt.io/) is decoded and nothing's wrong. 

I was having an Openssl() error using `RS256` so I changed it to `HS256` and that error was fixed. But I still have the error below?

```
> auth/invalid-custom-token
> The custom token format is incorrect. Please check the documentation.
```

```
require_once('../vendor/autoload.php');
use \Firebase\JWT\JWT;

$service_account_email = env('ACCOUNT_EMAIL');
$private_key = env('ACCOUNT_SECRET');

class generateToken
{
    public static function generateNewToken($mysqli, $userID, $email)
    {
        global $service_account_email, $private_key;

        $name = '';
        $lastname = '';
        $hostOption = '';
        $now_seconds = time();

        $selectUserData = "SELECT username, lastname, hostOption FROM signup WHERE id = ? ";
        $stmt = $mysqli->prepare($selectUserData);
        $stmt->bind_param('i', $userID);
        $stmt->execute();
        $stmt->store_result();
        $stmt->bind_result($name, $lastname, $hostOption);
        $stmt->fetch();

        $payload = array(
            "iss" => $service_account_email,
            "sub" => $service_account_email,
            "aud" => "https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit",
            "iat" => $now_seconds,
            "exp" => $now_seconds + (60 * 60),  // Maximum expiration time is one hour
            "uid" => strval($userID),
            "claims" => array(
                "username" => $name,
                "lastname" => $lastname,
                "email" => $email,
                "hostOption" => $hostOption,
            )
        );

        return JWT::encode($payload, $private_key, 'HS256');
    }
}
```

**Comment by madsongr** [comment]
Just solved it! Reading [this issue](https://github.com/firebase/php-jwt/issues/98) I could work with `RS256` just using double quotes instead of single quotes in `$private_key` and I don't get invalid token error anymore.
