### ISSUE TITLE
Error trying to connect to Firebase

### ISSUE THREAD

**Issue by saffabook** [firebase/php-jwt#128]
I have installed the package, then I have followed these instructions. https://firebase.google.com/docs/auth/admin/create-custom-tokens
at the bottom you will see the jwt-php example, then got my account's email address and private key, generated a token and when putting it at the end of the url ie ?auth="generatedtoken"
I get the error below.  What steps am I missing?
{
    "error": "Expected an ID token, but was given a custom token."
}

**Comment by bshaffer** [comment]
Hello! You need to use the `loginWithCustomToken` method on the client side to exchange your `custom token` for an `ID token`. Then, the ID token can be used in the URL. See [Sign in using custom tokens on clients](https://firebase.google.com/docs/auth/admin/create-custom-tokens#sign_in_using_custom_tokens_on_clients) for more information.

If you think there is a problem with the documentation, click **Send Feedback** in the top right corner of [the page](https://firebase.google.com/docs/auth/admin/create-custom-tokens) and tell us the problem.
