### ISSUE TITLE
Fatal error: Class 'Firebase\JWT' not found on line 18

### ISSUE THREAD

**Issue by Krunal-Gosalia** [firebase/php-jwt#130]
Step 1: Running command "composer require firebase/php-jwt"
Step 2: Creating new test.php file for verifying

[JWT_App.zip](https://github.com/firebase/php-jwt/files/675351/JWT_App.zip)

Running file using XAMPP server
Error:- Fatal error: Class 'Firebase\JWT' not found on line 18

**Comment by bshaffer** [comment]
Hey @Krunal-Gosalia! Try this:

```php
<?php
// include composer's autoloader so it can find the JWT classes:
require_once __DIR__ . '/vendor/autoload.php';

// your code...
use \Firebase\JWT\JWT;

$key = "test";
$token = array(
    "iss" => "http://example.org",
    "aud" => "http://example.com",
    "iat" => 1356999524,
    "nbf" => 1357000000
);

// ... the rest of your code ...
```
