### ISSUE TITLE
Cannot install: "these conflict with your requirements or minimum-stability"

### ISSUE THREAD

**Issue by ashleyliu31** [firebase/php-jwt#133]
Hello,
I tried to install with composer but the following error messages showed:
 Problem 1
    - firebase/token-generator v3.0.0 requires firebase/php-jwt ^3.0 -> satisfiable by firebase/php-jwt[v3.0.0] but these conflict with your requirements or minimum-stability.
    - firebase/token-generator v3.0.0 requires firebase/php-jwt ^3.0 -> satisfiable by firebase/php-jwt[v3.0.0] but these conflict with your requirements or minimum-stability.
    - firebase/token-generator v3.0.0 requires firebase/php-jwt ^3.0 -> satisfiable by firebase/php-jwt[v3.0.0] but these conflict with your requirements or minimum-stability.
    - Installation request for firebase/token-generator ^3.0 -> satisfiable by firebase/token-generator[v3.0.0].

Any idea on how to fix this? Alternatively, is there a way to use this library without composer? Thanks!

**Comment by bshaffer** [comment]
Hi @ashleyliu31. This is strange, as I don't see any conflicts. Try removing your `vendor` directory and installing again. 

Do you have any other dependencies in your project?

**Comment by tuupola** [comment]
How does your `composer.json` look?

**Comment by ashleyliu31** [comment]
{
    "config": {
        "disable-tls": false
    },
    "require": {
        "firebase/token-generator": "^3.0"
    }
}

i found these codes in the file. Any clues?

**Comment by ashleyliu31** [comment]
I tried removing the vendor directory and kreait/firebase-php and nothing worked.
However, when i required firebase/php-jwt ^3.0 (with ver. number) it worked! Perhaps something is incompatible with 4.0?

**Comment by bshaffer** [comment]
So I believe the issue is you're using `$ composer require firebase/php-jwt`, which tries to use the latest major version. For this library, the latest major version is `4.0`, but the `kreait/firebase-php` library uses `3.0`. So, if you want to explicitly include `firebase/php-jwt` in your `composer.json`, you'll need to specify you want to use the `3.0` version:

```json
{
    "require": {
        "kreait/firebase-php": "^2.0",
        "firebase/php-jwt": "^3.0"
    }
}
```

** OR **

```sh
composer require firebase/php-jwt:^3.0
```

**Note**: Composer already installs `firebase/php-jwt:^3.0` implicitly as a dependency of `kreait/firebase-php`, so you don't need to add that line at all if you don't want to.

I hope this makes sense! Let me know if you have any other questions.

*Steps to reproduce:*

```sh
$ composer require kreait/firebase-php
Using version ^2.0 for kreait/firebase-php
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing mtdowling/jmespath.php (2.4.0)
    Downloading: 100%         

  - Installing guzzlehttp/promises (v1.3.1)
    Loading from cache

  - Installing psr/http-message (1.0.1)
    Loading from cache

  - Installing guzzlehttp/psr7 (1.3.1)
    Loading from cache

  - Installing guzzlehttp/guzzle (6.2.2)
    Loading from cache

  - Installing psr/cache (1.0.1)
    Loading from cache

  - Installing firebase/php-jwt (v3.0.0)
    Loading from cache

  - Installing google/auth (v0.11.1)
    Loading from cache

  - Installing firebase/token-generator (v3.0.0)
    Downloading: 100%         

  - Installing kreait/firebase-php (2.0.2)
    Downloading: 100%         

Writing lock file
Generating autoload files
✔ /tmp/composertest 
10:42 $ composer require firebase/php-jwt
Using version ^4.0 for firebase/php-jwt
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - firebase/token-generator v3.0.0 requires firebase/php-jwt ^3.0 -> satisfiable by firebase/php-jwt[v3.0.0] but these conflict with your requirements or minimum-stability.
    - firebase/token-generator v3.0.0 requires firebase/php-jwt ^3.0 -> satisfiable by firebase/php-jwt[v3.0.0] but these conflict with your requirements or minimum-stability.
    - firebase/token-generator v3.0.0 requires firebase/php-jwt ^3.0 -> satisfiable by firebase/php-jwt[v3.0.0] but these conflict with your requirements or minimum-stability.
    - Installation request for firebase/token-generator (locked at v3.0.0) -> satisfiable by firebase/token-generator[v3.0.0].


Installation failed, reverting ./composer.json to its original content.
```

*Steps to fix:*

```sh
$ composer require kreait/firebase-php
Using version ^2.0 for kreait/firebase-php
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing mtdowling/jmespath.php (2.4.0)
    Loading from cache

  - Installing guzzlehttp/promises (v1.3.1)
    Loading from cache

  - Installing psr/http-message (1.0.1)
    Loading from cache

  - Installing guzzlehttp/psr7 (1.3.1)
    Loading from cache

  - Installing guzzlehttp/guzzle (6.2.2)
    Loading from cache

  - Installing psr/cache (1.0.1)
    Loading from cache

  - Installing firebase/php-jwt (v3.0.0)
    Loading from cache

  - Installing google/auth (v0.11.1)
    Loading from cache

  - Installing firebase/token-generator (v3.0.0)
    Loading from cache

  - Installing kreait/firebase-php (2.0.2)
    Loading from cache

Writing lock file
Generating autoload files
✔ /tmp/composertest 
10:48 $ composer require firebase/php-jwt:^3.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
✔ 
```
