### ISSUE TITLE
Not compatible with PHP 5.3 as stated

### ISSUE THREAD

**Issue by tebinu** [firebase/php-jwt#139]
JWT.php
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
ERROR | The function hash_equals() is not present in PHP
     |       | version 5.5 or earlier
ERROR | The function json_decode() does not have a parameter
     |       | "options" in PHP version 5.3 or earlier

**Comment by tuupola** [comment]
> ERROR | The function hash_equals() is not present in PHP | | version 5.5 or earlier

There is a [check](https://github.com/firebase/php-jwt/blob/master/src/JWT.php#L236-L238) whether `hash_equals()` exists or not. Pure php implementation is used as fallback.

> ERROR | The function json_decode() does not have a parameter | | "options" in PHP version 5.3 or earlier

There is a [check](https://github.com/firebase/php-jwt/blob/master/src/JWT.php#L262-L267) for PHP version to see if `json_decode()` supports options. Fallback is used for PHP versions older than 5.4.
