### ISSUE TITLE
Return false instead of throwing DomainException on openssl_verify returning 0

### ISSUE THREAD

**Issue by Nolhian** [firebase/php-jwt#141]
Why is it throwing a [DomainException](https://github.com/firebase/php-jwt/blob/master/src/JWT.php#L229) when the signature is incorrect in the static verify method ?
It should just return false which will in turn throw the correct [SignatureInvalidException](https://github.com/firebase/php-jwt/blob/master/src/JWT.php#L109), shouldn'it ?

EDIT : Also openssl_verify returns -1 on error. If that happens the $signature will be returned [here](https://github.com/firebase/php-jwt/blob/master/src/JWT.php#L231) and thus the signature will be marked as valid.

**Comment by rhamses** [comment]
Hi, just wondering... Have you tried put `JWT::decode($jwt, $key, array('HS256')` into a **`try{}catch{$e}`** block? That solved the problem for me here.
