### ISSUE TITLE
Encode example broken

### ISSUE THREAD

**Issue by gbittmann** [firebase/php-jwt#147]
The example  from https://firebase.google.com/docs/auth/admin/create-custom-tokens

```
// Requires: composer require firebase/php-jwt
use Firebase\JWT\JWT;

// Get your service account's email address and private key from the JSON key file
$service_account_email = "abc-123@a-b-c-123.iam.gserviceaccount.com";
$private_key = "-----BEGIN PRIVATE KEY-----...";

function create_custom_token($uid, $is_premium_account) {
  global $service_account_email, $private_key;

  $now_seconds = time();
  $payload = array(
    "iss" => $service_account_email,
    "sub" => $service_account_email,
    "aud" => "https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit",
    "iat" => $now_seconds,
    "exp" => $now_seconds+(60*60),  // Maximum expiration time is one hour
    "uid" => $uid,
    "claims" => array(
      "premium_account" => $is_premium_account
    )
  );
  return JWT::encode($payload, $private_key, "RS256");
}
```
Decode result:
> "kid" empty, unable to lookup correct key

If you modify the call to include the 'private_key_id' from the service account json file.

`JWT::encode($payload, $private_key, "RS256", $private_key_id);`

Decode result:
> Warning: openssl_verify(): supplied key param cannot be coerced into a public key

The example is either broken, or their needs to be a special decode example that maps to creating a custom token.

**Comment by CharltonSantana** [comment]
@gbittmann This is because the example has `$private_key = "-----BEGIN PRIVATE KEY-----...";`. You need to replace this with your private key which is in the firebase service account key file. 

I would suggest your PHP code to open this file and read the private key instead of putting it directly in your source code. 

```php
$path = 'path/to/serviceAccountKey.json';
$firebaseConfig = json_decode(file_get_contents($path), true);
$private_key = $firebaseConfig['private_key'];
```
