### ISSUE TITLE
Decoding problem

### ISSUE THREAD

**Issue by goodrickstar** [firebase/php-jwt#153]
I have validated the JWT via the web. With secret base64 encoded checked it passes, unchecked it does not.

io.jsonwebtoken:jjwt:0.7.0

```
String compactJws = Jwts.builder()
                .claim("devId", getDeviceId())
                .signWith(SignatureAlgorithm.HS256, "testing")
                .compact();
        logger.i(compactJws);
```
returns the token: eyJhbGciOiJIUzI1NiJ9.eyJkZXZJZCI6Ijc4MGQ1YWRlMzMwNGVhZmEifQ.XIKxG1xZbuMD8FRIAJ735LNbhodAj1a7pMZ6o3IF0ig

[]https://jwt.io/
  
![example](https://user-images.githubusercontent.com/12790922/26977940-9bd261c6-4cf7-11e7-8f80-0ac003ef2c86.png)

```
use \Firebase\JWT\JWT;
$jwt = "eyJhbGciOiJIUzI1NiJ9.eyJkZXZJZCI6Ijc4MGQ1YWRlMzMwNGVhZmEifQ.XIKxG1xZbuMD8FRIAJ735LNbhodAj1a7pMZ6o3IF0ig";
$key = "testing";
$decoded = JWT::decode($jwt, $key, array('HS256'));
print_r($decoded);
```

returns Uncaught exception 'Firebase\JWT\SignatureInvalidException' with message 'Signature verification failed'

**Comment by lindelius** [comment]
Shouldn't `$key` be "testing" like on the screenshot, though? And not "passing".

**Comment by goodrickstar** [comment]
I've updated my code, with the proper screenshot and included the Android library i'm using to create the token.

**Comment by goodrickstar** [comment]
I've also tried
`$key = base64_encode("testing");`

**Comment by goodrickstar** [comment]
UPDATE:
using the php to generate the JWT then Decoding I end up with a different token. The difference when verifying is "secret base64 encoded". How to account for secret base64 encoded on the PHP side?

**Comment by goodrickstar** [comment]
The answer was I was missing the "typ":"JWT" header and having to decode the key
    

```
    Map<String, Object> header = new HashMap<>();
        header.put("typ", Header.JWT_TYPE);
        .setHeader(header)
```


PHP SIDE

     `$decoded_array = (array) JWT::decode($jwt, base64_decode($key), array('HS256'));`
