### ISSUE TITLE
Should i save in sessions or cookies

### ISSUE THREAD

**Issue by kreshnik01** [firebase/php-jwt#154]
Where do i save my generated token, in sessons or cookies?

**Comment by akeeman** [comment]
Does [this](https://jwt.io/introduction/) help?

**Comment by kreshnik01** [comment]
@akeeman No it's not because this example it's for node.js and I have to use JWT on PHP.

**Comment by kreshnik01** [comment]
@akeeman No it's not because this example it's for node.js and I have to use JWT on PHP.

**Comment by Tom29** [comment]
If you store it in session, it might be expired after session has expired.
Then user need to re-login to get other jwt.
Store it in cookie then doesn't need to retrieve other jwt until cookie / token expired

**Comment by pramodwerea** [comment]
what about storing them in localStorage?

**Comment by fikoborquez** [comment]
@pramodwerea should work too

**Comment by SvenRtbg** [comment]
http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/
http://cryto.net/~joepie91/blog/2016/06/19/stop-using-jwt-for-sessions-part-2-why-your-solution-doesnt-work/
