### ISSUE TITLE
do we need to verify payload (iat,nbf,exp) ourselves 

### ISSUE THREAD

**Issue by pramodwerea** [firebase/php-jwt#170]
After decoding the payload I am getting all the payload data (aud,iat,nbf etc). Now is there any function to call to see if the token is still valid w.r.t. exp or nbf or exp. Or it does automatically when we do deocoding of token? Because I have **iat** and **nbf** value set as in the given example which is expired unix timestamp, it decodes correctly.

Also, how can we prevent request **replay attack** if someone knows the token?

**Comment by HenryNe** [comment]
You nor need to check the **nbf** and **exp**. You will gt an exception, if the token is out of time.
The **aud** is not checked by this library. The application (you) must do it self after decoding.

Against the replay attack: Put some more information in the jwt, for example the source IP port. Of curse, who has the token, can send the information. Sou you should send it only thought secure (https). Find a good article "Pros and cons in using JWT" from Rahul Golwalkar.

**Comment by pramodwerea** [comment]
@HenryNe thanks for the information!
