### ISSUE TITLE
How to invalid the token on logout

### ISSUE THREAD

**Issue by pramodwerea** [firebase/php-jwt#171]
how to prevent someone not to use already used token. My use case is when a user log-out the application I want to invalid the used token so that next time no one can use it if someone has taken it for some reason.

Is there a way to blacklist the used token?

**Comment by Tom29** [comment]
After user logged out, delete the token.
If you want it get expired , only 1 way is storing it in the db, then manage it.

**Comment by pramodwerea** [comment]
@fikoborquez thanks a lot, I will go through the links! @Tom29 yes I am deleting the token after logging out, my concerned is when a user does not log out manually.

**Comment by LuisMejiaF** [comment]
You have to specify the `exp` claim, which MUST be the time when the token will be expired. 
Then when you tried to decode the token with `Firebase\JWT\JWT::decode()`, you will get a **ExpiredException**.

**Comment by SvenRtbg** [comment]
Generally you cannot rely on the token being deleted. Limit the time range where the token is valid to enforce a logout after a certain time. 

Also note that JWT is not suited to be used to store session data on the client:
http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/
http://cryto.net/~joepie91/blog/2016/06/19/stop-using-jwt-for-sessions-part-2-why-your-solution-doesnt-work/

JWT is great for sending use-once or use-in-limited-time messages from one server to the other via the client. It will make the message tamper-proof while being in transit, and also readable for the client (no encryption, the content is sent base64-encoded, which is as good as clear text). But after all, it is a token.

**Comment by segunmicheal27** [comment]
re-invalidation of token is very important the flaw i find out in this library, is the attacker get access to the previous token the server is liable to gain access login regardless of your time limit you assign the token, for the attacker are very smart that is why we need to revoke the token. Just vise visa
And i find out there is no claim algorithm included in this library, just to make token claim access

**Comment by SvenRtbg** [comment]
@segunmicheal27 If you need to revoke access when the user logs out, there is a solution for you that is already invented: It is called "session", and it depends on server side state tracking together with a random string in a cookie acting as the access token.

Don't use JWT based libraries for this. The thing you want: JWT cannot deliver it.
