### ISSUE TITLE
Firebase\JWT\ExpiredException should return a 401 status code

### ISSUE THREAD

**Issue by tgrowden** [firebase/php-jwt#173]
Firebase\JWT\ExpiredException should return a 401 status code; currently it returns a 500 status code. As this is dealing with auth and not an internal server error, 401 seems more appropriate.

**Comment by royanon** [comment]
In the decode statement, use try and it will not return a 500 status. Handle it with 401. e.g.
try{
 $decoded = JWT::decode($accesstoken, $this->publicKey, array('RS256'));
} catch (\UnexpectedValueException $e){
 error_log("UnexpectedValueException:[" . $e->getMessage()."]");
} catch (\Exception $e) {
 error_log("GeneralException:[" . $e->getMessage()."]");
}
if(!$decoded->uid){
 header('HTTP/1.1 401 Unauthorized');
 exit;
}
Then, do not need to make any changes to the library.

**Comment by bshaffer** [comment]
Can you rebase this commit? Doing so will allow the test to pass!
