### ISSUE TITLE
Someone is wrong with validating google tokens {Signature verification failed}

### ISSUE THREAD

**Issue by eddie-g** [firebase/php-jwt#175]
I get the following error when validating my google token,
```
An uncaught Exception was encountered  Type: Firebase\JWT\SignatureInvalidException  
Message: Signature verification failed  
Filename: /var/www/Forge/vendor/firebase/php-jwt/src/JWT.php  
Line Number: 112
```

Yet when i request this url https://www.googleapis.com/oauth2/v2/tokeninfo?id_token={mytoken} with the value of mytoken I get a valid request with data back.

This is the line that's causing the error: 
Tokens value here is correct, verified against googles servers. 
`$payload = $this->jwt->decode($idToken, $rsa->getPublicKey(),array('RS256'));`

Line 112
`if (!static::verify("$headb64.$bodyb64", $sig, $key, $header->alg)) { 
throw new SignatureInvalidException('Signature verification failed'); }`

**Comment by fikoborquez** [comment]
[this](https://stackoverflow.com/questions/25086410/what-part-of-the-key-object-do-i-pass-into-openssl-verify-to-verify-a-google-s) may help you

**Comment by LukeTowers** [comment]
The signature verifications when it goes through the GoogleClient->authenticate($code) workflow. The JSON web token that the Google API Client library provides Firebase\PHP-JWT is valid (and will work correctly when verified direct with Google (https://www.googleapis.com/oauth2/v2/tokeninfo?id_token=), however when PHP-JWT attempts to base64decode() the token's signature, it sometimes fails, returning an invalid base64encoded string.

**Comment by LukeTowers** [comment]
I have no idea yet what is causing the sporadic failure of the signature being decoded.

**Comment by JorisDebonnet** [comment]
We have also been having this problem. Has anyone been able to shed any light on it? 

It "usually works" but "sometimes" it doesn't. Our API log shows the **exact same input** going into the method, but one time it works, and another there's a Firebase\JWT\SignatureInvalidException saying "Signature verification failed". 

(note: we are using google/apiclient, which in turn uses this package.)

**Comment by LukeTowers** [comment]
@JorisDebonnet do you know which function the code uses to verify the signature in your case? https://github.com/firebase/php-jwt/blob/master/src/JWT.php#L228

**Comment by JorisDebonnet** [comment]
@LukeTowers I put some logging there, and seems like it's using openssl / SHA256. So `openssl_verify` returns `0`.

Does that mean the `$signature` is not constructed correctly, and/or should I file this issue under google/apiclient?

**Comment by LukeTowers** [comment]
@JorisDebonnet what happens is that the signature is pulled from the JWT here: https://github.com/firebase/php-jwt/blob/master/src/JWT.php#L87, however it sometimes fails to properly base64decode the signature. I can't remember exactly what was causing the failure, but basically that method was returning an invalid base64 decoded string. I would start by attempting to debug that method and each step of the process that passes the signature to the openssl_verify function. I don't believe it is an error with the apiclient, but it could be. It's no longer an active issue for me since my code basically just retries validation after receiving this exception now and that works 99% of the time. 

If you could spend some time debugging those methods further to find out the root cause of the issue, that would be fantastic though!

**Comment by sam17896** [comment]
I am having same issue right now... its is working on my local server but when i deploy my api to the server it throw "Signature Verification Failed" any workaround ?

**Comment by LukeTowers** [comment]
@sam17896 you could be having a separate issue if your verification is consistently failing. Anything from your server having an incorrect version of OpenSSL to your configuration being different between local and production. Did you try to replicate the steps of https://github.com/firebase/php-jwt/issues/175#issue-255404904 to see if this is actually your issue?

**Comment by JorisDebonnet** [comment]
I finally fixed my issue for me with a single line...
`composer update google/apiclient`

Suddenly the login wasn't working at all anymore for me, so I spent over an hour trying to debug it further, but updating google/apiclient from 2.2.0 to 2.2.1 somehow fixed the issue.
