### ISSUE TITLE
How to distinguish UnexpectedValueException thrown by php-jwt from the same exception thrown from another place?

### ISSUE THREAD

**Issue by chimit** [firebase/php-jwt#176]
I catch all app exceptions in one place. It's easy with **ExpiredException** or **SignatureInvalidException**, but php-jwt also uses an **UnexpectedValueException**. It's a general SPL's exception and it may be used in other packages. How to distinguish them?

**Comment by fikoborquez** [comment]
Can you give an example of what you want to achieve?

**Comment by chimit** [comment]
I'm using this package in Laravel and handle all exceptions in `App/Exceptions/Handle.php` like this:
```php
    public function render($request, Exception $e)
    {
        // return parent::render($request, $e);

        switch (true) {
            case $e instanceof ExpiredException:
                return 'Token expired!';
                break;

            case $e instanceof SignatureInvalidException:
                return 'Token signature invalid!';
                break;

            case $e instanceof UnexpectedValueException:
                return 'Wrong token format!';
                break;

            ...
```
It works, but I'm afraid if some another package throw the same `UnexpectedValueException` the server response would be irrelevant.

**Comment by fikoborquez** [comment]
Maybe you could check what file is creating the exception. You can use the method [getFile](http://php.net/manual/en/exception.getfile.php) from Exception class.

**Comment by chimit** [comment]
Yes, it's a way to solve this problem, but I think it would be better to use only custom exceptions to avoid any dirty checking.

@robertdimarco could you, please, comment?

**Comment by lindelius** [comment]
@chimit feel free to use [my library](https://github.com/lindelius/php-jwt) if you need this functionality. I've got a slightly different (OOP) aproach, though, but I think I've included enough documentation to explain how to use it :)

**Comment by yash30201** [comment]
Closing as this seems answered.
