### ISSUE TITLE
[!!!ERROR!!!] Fix this pls.

### ISSUE THREAD

**Issue by scwl-studio** [firebase/php-jwt#181]
sorry, maybe your make mistake in this part of your code?
`if (isset($payload->nbf) && $payload->nbf > ($timestamp + static::$leeway))`
this means that if the current date is less than the end, then the token will not work
but the same condition is repeated for the creation date:
`if (isset($payload->iat) && $payload->iat > ($timestamp + static::$leeway))`
that is, the token will always not work.
correct, if I'm wrong.

i fix in own project this to `if (isset($payload->nbf) && $payload->nbf < ($timestamp + static::$leeway))` and it works correctly.

**Comment by lindelius** [comment]
`nbf` is ”not before” and means that the token should not be valid before the given timestamp, i.e. the `nbf` value *must* be less than the current time (plus possible leeway time) in order to be considered valid.

The library is correct, your ”fixed” version is not.

**Comment by scwl-studio** [comment]
Ok. Thx.
I made a mistake)

**Comment by lindelius** [comment]
No worries :)
