### ISSUE TITLE
Add ES256 to the list of supported agorithms

### ISSUE THREAD

**Issue by bshaffer** [firebase/php-jwt#183]

**Comment by beamerblvd** [comment]
I literally got this to work with one line of code change: Adding `'ES256' => array('openssl', 'SHA256'),` to `$supported_algs` in `JWT.php`. With that one change, I was able to use this to sign Apple Push Notification requests. Without that change, I can't.

I'll put together a pull request.

**Comment by beamerblvd** [comment]
Posted #239.
