### ISSUE TITLE
Private Key & Public Key

### ISSUE THREAD

**Issue by rahendz** [firebase/php-jwt#185]
first, sorry for my bad english. I'm indonesian by the way. So is there anyone here could explain how to create private and public key. i know some of you will tell me that use the ssh_keygen to generate private or public key. But what i ask is, how create public keys that could decode the encoded payloads using private key.

Is all public key generated from the private key, or else? if its generated then how create private key and how to generate public key again and again from private key? Or if i have wrong concept of private and public keys please tell me the right concept.

**Comment by rafaelrenanpacheco** [comment]
To generate keys, take a look at: http://php.net/manual/en/function.openssl-pkey-new.php

The first example shows how to generate a public key from a private key.

Then you can use those keys in php-jwt.

:+1:

**Comment by rahendz** [comment]
@rafaelrenanpacheco thanks for the answer, so basically it could generated different public key again and again from one private key?

**Comment by HenryNe** [comment]
I can not speak for the functions in function.openssl-pkey-new.php. Typically for private and public keys, you would get the same public key every time you use the same private key.

If you have an private key, you can create the public from this with openssl:
`openssl rsa -in private.key -pubout > pubkey.key`

in issue #116 we spoken about using keys, and creating them. In [comment](https://github.com/firebase/php-jwt/issues/116#issuecomment-260809197) have an example, there the public key was extracted from private key.

**Comment by yash30201** [comment]
Closing as this seems answered.
