### ISSUE TITLE
Fatal error:  Uncaught Firebase\JWT\ExpiredException

### ISSUE THREAD

**Issue by mlenoir42bis** [firebase/php-jwt#194]
Hello,

this line generate a fatal error :
 $tokenArray = JWT::decode($token, SECRET_KEY, ['HS256']);

error message :
<b>Fatal error</b>:  Uncaught Firebase\JWT\ExpiredException: Expired token in /Library/WebServer/Documents/api/app/vendor/firebase/php-jwt/src/JWT.php:134

I integrate the class like that with composer :

require_once ROOT . "/app/vendor/autoload.php";
use \Firebase\JWT\JWT;

Thank you for your answers

**Comment by alexandre-le-borgne** [comment]
Hi, 

Same issue here.
The decoded claim 'exp' is badly decoded. (also 'iat' claim)

I tested my token on this site (https://jwt.io/) and my data is correct: the token has not expired. While, just after being generated, the timestamp is already invalid according to JWT :: decode

**exp on https://jwt.io/ :** 1517909152
**exp after JWT::decode() :** 1517906978 (invalid)


**id_token :** 
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImMyYzE2OWIzMGM4OGE3NTAxZGNmMTZmY2NmZWNiMWY2In0.eyJpc3MiOiJlLXN5bmFwcy5jb20iLCJzdWIiOiJyWmU1MmJPZDVqQVZhajJYOFJocDd3bFg2VkJHNFBaQnVnTnF5VDMzUFRYbGlOdDNkdjhsUWljdDNwVG9EejZUcjNqTFhodEc0NVEzcmZta3hEcnVSYXpJaFRETkpmZU56a0NHIiwiYXVkIjoiNDZqZzV4Z2xoMjJvNDgwazhjMGtrb2tnZ3dzb3M0MGM4Y2tzZ2dzbzRvZ29zNGNjazgiLCJpYXQiOjE1MTc5MDgyNTIsImV4cCI6MTUxNzkwOTE1MiwiYXV0aF90aW1lIjoxNTE3OTA4MjUyfQ.qvFLIC7kOqgtTJb4os5S1aDlnxe6eBU25rpwOF59eh1tfMer7u0Utc7KTCZfa8Hs7kW2bA2CQkthj1Z61GlQdCccf5jYfTdlY3pDKP3pWkVhkcBXq9LM2OHRnElAjWtasNg9AVtcD42M05oDNgFz4gvo2OHEa7L9IhVJqgey7jmIn_rbbyKM-OEkhfMsrPJSt4PXvUzI_s-lq_aDDQATMHQyD4nVb7EzXWm4IhYGjlVirJ4WcE3Ts5J7s5UZIsEZHuuLEVOiwxkGjvk20PA6slxVRwiwz5Ue2Gs6YxacovkZAFsyU8lI1NsI1B8SSVdyKp5guR17md19ddg668ClLRQaQaCfeYW3Fr4vQcvxa_KbkaG7pLmGm96UxwE4UfjZaQM3rvEqP4NxgZTDMvrlb80HkyImlQpiWyJRHNd2yWRHSsFuXx28YldQrVCWNsdfSHNHV0rXOSDnvXLSZN_n3V8hoBUEKU9aiPnKiyc28njX2pxOIc3aPwXf8ZqIyysfD1_fRLqGQGuf-4SWnsnGMBRIcU-6RxjbtFFVQRwD8xEKeaj_34lFt5yLGhs4C5dqMKP2sqd0zFbQ5uEgel8Jn7KbPIzU6JzUVd9q5wysaq-PzNJ2a8XFRwUaoBBITpPCMptu2vXMm7jhV7ukbtRx3KLp5eC7wP-nKNXOFRMFl2Q

**key :**
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvLBw2os1a5TciHRtzg8R52hjKfoOLwrpPMSyIqqrmfs86O1X1cgBm8cFD\/25ev+d6qmpXlzvj0LJKdtPibj7vlmzRLtUoEqCr95\/oM8YPl\/A5575GsItuBDCx5sn3jCtjEnaSGlSHZ44x4H2IVotyfE5AeOIUvviLG+JN5y62QXJqnjC7+g9cAkrSJVTpqSQP6S8rVh2nHXRl8PO\/0c+wI0Et5r1pzusHA2rS4N3wNqhMDCZvnvb8MHYsWWo5mOH4b9vlpuKl3JxQ1EQ5IWG\/gBVq5\/hvSWqZAyPHTQt9rBlXfKDrCv2clIy\/ByHkoRR2CRgUn9qLu0W1gg\/P29SoC6rnIdycnrRJeb+9X\/zwplNjQ6+aOog6ay0OHvUSFaBjEIrZfyjR15VlnqT0g4zyMcC6\/zLPtlpaf+s9y522lehVmlEGJdjS1gUlp8lBUH64U51eCUIgsgf3ziL9DAutIZ+1iQLwXhJpDVDECLeeeHVfFG6BM8ZAHEbxErzwfdikrXgd7KKlc7UDtzs53cUdgHeQwnnbBhe74W8WXjk+tlJNw6du3bEvP11CnW02vkWF32EU4OJIV\/mbhQBk71MYJ1S2TOspC0Yl8vJDgBDZLquyDywiL06oyQr72\/bDmMf4FnMVGCpudaReJdFOneX+fVgI0ZBCQBTfTarByeLmD0CAwEAAQ==
-----END PUBLIC KEY-----

**Comment by alexandre-le-borgne** [comment]
You should debug the payload->exp at JWT.php:132 and use https://jwt.io/ to compare the claim exp of your id token.

**Comment by mlenoir42bis** [comment]
my token is good. This is the class that is not recognized

**Comment by alexandre-le-borgne** [comment]
Are the dates given by the library and by jwt.io the same?

**Comment by mlenoir42bis** [comment]
the fatal error does not allow any return of the decode function

**Comment by mlenoir42bis** [comment]
the fatal error does not allow any return of the decode function

**Comment by alexandre-le-borgne** [comment]
This is why you need to var_dump(payload->exp);die; at JWT.php:132 in your vendors

**Comment by mlenoir42bis** [comment]
OK, thanks. by changing the location of the files it works. it's probably because of loading the class of my micro-frameworck

**Comment by Agneswanjiku** [comment]
I don't get the idea on what logic you used to solve the error at the postman end...
