### ISSUE TITLE
how to use it in codeigniter3?

### ISSUE THREAD

**Issue by michaelzhouh** [firebase/php-jwt#197]
how to use it in codeigniter3?

**Comment by rps-repo** [comment]
This assumes you have already installed the library with composer.

`<?php
defined('BASEPATH') OR exit('No direct script access allowed');

use \Firebase\JWT\JWT;

class Myclass extends CI_Controller
{

    public function index()
    {
        $privateKey = file_get_contents('/path/to/private.key');

        $publicKey = file_get_contents('/path/to/pubkey.key');

        $token = array(
            "iss" => "example.org",
            "aud" => "example.com",
            "iat" => 1356999524,
            "nbf" => 1357000000
        );

        $jwt = JWT::encode($token, $privateKey, 'RS256');
        echo "Encode:\n" . print_r($jwt, true) . "\n";

        $decoded = JWT::decode($jwt, $publicKey, array('RS256'));

        /*
         NOTE: This will now be an object instead of an associative array. To get
         an associative array, you will need to cast it as such:
        */

        $decoded_array = json_decode(json_encode($decoded), TRUE);;
        echo "Decode:\n" . print_r($decoded_array, true) . "\n";
        
    }
}`
