### ISSUE TITLE
how use it on yii2?do someone use that before?

### ISSUE THREAD

**Issue by mikeching** [firebase/php-jwt#198]
how use it on yii2?do someone use that before?thanks

**Comment by almirb** [comment]
Hi!

I'm using this extension:
[https://github.com/Yemsheng/yii2-jwt](https://github.com/Yemsheng/yii2-jwt)

**Comment by yash30201** [comment]
Hoping the above extension helped you and thus closed this. Please reopen if this issue still persists.
