### ISSUE TITLE
Missing @throws in JWT::verify

### ISSUE THREAD

**Issue by SkylerLS** [firebase/php-jwt#213]
The `openssl_verify` method will die if the `$key` passed in cannot be coerced to a valid public key.
I discovered this in a unit test where I pass `JWT::decode` some invalid bogus public `$key` like `potato`. Then when the call cascades down to `JWT::verify` and eventually to `openssl_verify`, the call dies with a fatal `ErrorException` having a message of `openssl_verify(): supplied key param cannot be coerced into a public key`.

I agree this should be a fatal exception and not caught as the caller of JWT should figure out what to do in that case but can the `@throws` tags be updated for `JWT::verify` to reflect the possible exceptions thrown?

Thanks!

**Comment by ajupazhamayil** [comment]
I see the latest code has `@throws` [here](https://github.com/firebase/php-jwt/blob/main/src/JWT.php#L291). So, closing this issue. Thank you for raising this.
