### ISSUE TITLE
RS256: Where does the $privateKey comes from?

### ISSUE THREAD

**Issue by andreszs** [firebase/php-jwt#215]
I'm trying to use php-jwt to verify user ID tokens from Firebase with [these instructions](https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_a_third_party_jwt_library).

However, I'm not sure where can I get the `$privateKey` for this. The example in README says nothing about where does this value comes from. Thanks in advance.

**Comment by sammyHa** [comment]
The private key is used from the firebase serviceAccount json file found in the firebase console to generate the token than use the public keys from google [here] to (https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com) verify the jwt token.

**Comment by sammyHa** [comment]
The privatekey is used from the firebase serviceAccount.json file to generate the token and can be download from the firebase console. to verify the token use the the public key from this [link](https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com).

**Comment by vikas-kumar-bhardwaj** [comment]
Is this public key  always constant or changes periodically. I mean we need to fetch this every time or can be stored.
