### ISSUE TITLE
Feature Request: Better documentation/ Read Me

### ISSUE THREAD

**Issue by Chad-Krause** [firebase/php-jwt#216]
I am not seeing great examples in the readme.

What does the code look like after you decode the jwt?

What happens if someone modifies a jwt, what does verify and decode do?

What do all the options do in encode?

When would I use sign? If I wouldn't, how come it's public?

What are the speeds of various encryption methods?

I know I could look through the source/run tests myself to determine most of these, but I shouldn't have to for a library like this

Any chance of updating it?

**Comment by lindelius** [comment]
Hi @Chad-Krause 
This library unfortunately doesn't seem like it's being maintained which is one of the reasons why I wrote [my own](https://github.com/lindelius/php-jwt). Feel free to check it out, and if you think the documentation is lacking something, let me know.

**Comment by vishwarajanand** [comment]
We are not looking at updating the docs to reflect these info.
Beyond the code samples provided in README, follow the tests and src folders.
