### ISSUE TITLE
I think this is bug

### ISSUE THREAD

**Issue by juragandotid** [firebase/php-jwt#217]
I'm try to encode from with RS256 (openssl) , and i'm get the encode token. and i'mt try to decode the token just using base64_decode, and i get the payload data.

please add some private key to decode the token.

**Comment by cottton** [comment]
> Do note that for signed tokens this information, though protected against tampering, is readable by anyone. Do not put secret information in the payload or header elements of a JWT unless it is encrypted.

https://jwt.io/introduction/

**Comment by bshaffer** [comment]
The JWT is used for authentication, and not for encryption. As mentioned by @cottton anything secret should be encrypted by hand inside the token and is not in the scope of this library.
