### ISSUE TITLE
Verify token structure before going to decode

### ISSUE THREAD

**Issue by ebernerd** [firebase/php-jwt#219]
```php
// for this example, $token is something being sent over HTTP to verify a user //

$myDecodedJWT = (array)JWT::decode($token, "secret", array("HS256"));
```

If $token is indeed a valid three segment JWT, everything works fine. However, if someone sends something like `"this_is_not_a_valid_JWT" over the wires, the function errors and prevents any further code operations. First question is this: can I apply a try/catch to the decoding process?

Secondly, I suggest a function - `JWT::verify($token)`. It verifies that the string `$token` has the correct structure for a JWT. It could be used like this:
```php
$token = GetTokenFromRequest();
if (JWT::verify($token)) {
  $myDecodedJWT = (array)JWT::decode($token, "secret", array("HS256"));
} else {
   return "This is not a valid token";
}
```

Unless I'm completely missing something 😛

**Comment by ebernerd** [comment]
I guess I have myself to blame, but I see that ::verify is already a function now - It would be nice to see a docs update to include this. Sorry to bother.

**Comment by cottton** [comment]
Its private `private static function verify($msg, $signature, $key, $alg)`.
As far as i read the code every exception thrown at `::decode` indicates that the token is invalid.

I too would like to have more options|methods. But i would like to see this to stay as simple as it is atm.
That was the reason i have chosen it.

For now you can say on almost every exception the token is invalid.

Here an overview of what is thrown on `::decode` atm:

    try {
        (new \Firebase\JWT\JWT())->decode($token, $key, $allowedAlgorithms);
    } catch (\InvalidArgumentException $e) {
        // Key may not be empty
    } catch (\Firebase\JWT\SignatureInvalidException $e) {
        // Signature verification failed
    } catch (\Firebase\JWT\BeforeValidException $e) {
        // Cannot handle token prior to <datetime>
    } catch (\Firebase\JWT\ExpiredException $e) {
        // Expired token
    } catch (\UnexpectedValueException $e) {
        // Wrong number of segments
        // Invalid header encoding
        // Invalid claims encoding
        // Invalid signature encoding
        // Empty algorithm
        // Algorithm not supported
        // Algorithm not allowed
        // "kid" invalid, unable to lookup correct key
        // "kid" empty, unable to lookup correct key
    } catch (\DomainException $e) {
        // Null result with non-null input --at json decode
        // Algorithm not supported --at verify
        // OpenSSL error: <error> --at verify
    } catch (\Exception $e) {
        // NA
    }

So you could just do that:

    try {
        (new \Firebase\JWT\JWT())->decode($token, $key, $allowedAlgorithms);
    } catch (\InvalidArgumentException $e) {
        // 500 internal server error
        // your fault
    } catch (\Exception $e) {
        // 401 unauthorized
        // clients fault
    }

**Comment by ebernerd** [comment]
Thank you for the very informed response!

**Comment by andreszs** [comment]
> 
> 
> Its private `private static function verify($msg, $signature, $key, $alg)`.
> As far as i read the code every exception thrown at `::decode` indicates that the token is invalid.
> 
> I too would like to have more options|methods. But i would like to see this to stay as simple as it is atm.
> That was the reason i have chosen it.
> 
> For now you can say on almost every exception the token is invalid.
> 
> Here an overview of what is thrown on `::decode` atm:
> 
> ```
> try {
>     (new \Firebase\JWT\JWT())->decode($token, $key, $allowedAlgorithms);
> } catch (\InvalidArgumentException $e) {
>     // Key may not be empty
> } catch (\Firebase\JWT\SignatureInvalidException $e) {
>     // Signature verification failed
> } catch (\Firebase\JWT\BeforeValidException $e) {
>     // Cannot handle token prior to <datetime>
> } catch (\Firebase\JWT\ExpiredException $e) {
>     // Expired token
> } catch (\UnexpectedValueException $e) {
>     // Wrong number of segments
>     // Invalid header encoding
>     // Invalid claims encoding
>     // Invalid signature encoding
>     // Empty algorithm
>     // Algorithm not supported
>     // Algorithm not allowed
>     // "kid" invalid, unable to lookup correct key
>     // "kid" empty, unable to lookup correct key
> } catch (\DomainException $e) {
>     // Null result with non-null input --at json decode
>     // Algorithm not supported --at verify
>     // OpenSSL error: <error> --at verify
> } catch (\Exception $e) {
>     // NA
> }
> ```
> 
> So you could just do that:
> 
> ```
> try {
>     (new \Firebase\JWT\JWT())->decode($token, $key, $allowedAlgorithms);
> } catch (\InvalidArgumentException $e) {
>     // 500 internal server error
>     // your fault
> } catch (\Exception $e) {
>     // 401 unauthorized
>     // clients fault
> }
> ```

This should be present in the **README** file, otherwise how are developers supposed to integrate the decode methods? Raising undocumented errors is not a very polite way of programming in any language.
