### ISSUE TITLE
Request for public function getHeader()

### ISSUE THREAD

**Issue by cottton** [firebase/php-jwt#220]
Im planning to add a PR - perhaps somebody else is already on it.

In the mean time - if somebody needs the header to get f.e. the "kid" offset - you can extend the JWT and add a new method like this:

    /**
     * Returns the access token header.
     *
     * @param string $accessTokenString
     *
     * @return array|null
     */
    public function getHeader($accessTokenString)
    {
        #todo getting the header data here (f.e. to get the "kid") -- create pull request to get header data back from JWT
        #code copied from JWT::decode
        $tks = explode('.', $accessTokenString);
        if (count($tks) != 3) {
            throw new \UnexpectedValueException('Wrong number of segments');
        }
        list($headb64, $bodyb64, $cryptob64) = $tks;
        if (null === ($header = JWT::jsonDecode(JWT::urlsafeB64Decode($headb64)))) {
            throw new \UnexpectedValueException('Invalid header encoding');
        }
        return json_decode(json_encode($header), true);
    }

Note: `json_decode(json_encode($header), true)` to get `array` out of a multidimensional `stdClass`.

**Comment by lindelius** [comment]
Hi @cottton 
I've created a [library](https://github.com/lindelius/php-jwt) that includes, among other things that this library is unfortunately missing, both a `getHeader()` and a `getHeaderField($field)` method.

**Comment by bshaffer** [comment]
This has now been added in the form of an optional; third `$headers` parameter in `decode`. This allows you to get the headers when you decode a JWT:

```php
// Pass a stdClass in as the third parameter to get the decoded header values
$decoded = JWT::decode($jwt, new Key($key, 'HS256'), $headers = new stdClass());
print_r($headers);
```

Be sure to upgrade to at least [v6.6.0](https://github.com/firebase/php-jwt/releases) to use this feature
