### ISSUE TITLE
BIGINT handling is broken

### ISSUE THREAD

**Issue by stevecoug** [firebase/php-jwt#223]
This is really two issues surrounding the library's handling of integers > 64-bit in the `JWT::jsonDecode()` method.

1. The check to make sure we're not using the JSON_C extension is obsolete; that library fixed the issue years ago, so it's okay to use it for BIGINT parsing
2. The regular expression is not very robust. For example, if given the following JSON string, it will break:
`{
    "username": "19180152::0518985564035248581be0f2a2a2c913",
    "test": 12345678901234567890
}`
It will actually add double quotes around a portion of the username string, like so:
`{
    "username": "19180152:: "0518985564035248581"be0f2a2a2c913",
    "test": 12345678901234567890
}`
This causes the resulting JSON string to fail to parse.

I considered various ways to fix the regular expression, but making it robust would be extremely difficult. I recommend just dropping support for BIGINT to String conversion for pre-5.4.

**Comment by ajupazhamayil** [comment]
I see the latest code uses [json_decode](https://www.php.net/manual/en/function.json-decode.php) [here](https://github.com/firebase/php-jwt/blob/main/src/JWT.php#L359).

I could not see the JSON_C check, but, I tested the second scenario and giving me the following result.

```
php > $input = '{ "username": "19180152::0518985564035248581be0f2a2a2c913", "test": 12345678901234567890 }';
php > $obj = \json_decode($input, true, 512, JSON_BIGINT_AS_STRING);
php > print_r($obj);
Array
(
    [username] => 19180152::0518985564035248581be0f2a2a2c913
    [test] => 12345678901234567890
)
```

This must have resolved after this bug has been raised. Thank you for raising this issue.  Closing this thread.
