### ISSUE TITLE
The RS256 example just Puzzled me.

### ISSUE THREAD

**Issue by yumi-cn** [firebase/php-jwt#225]
The RS256 example in the readme file can run in my runtime:

- OpenSSL Library Version: OpenSSL 1.0.2k 26 Jan 2017
- PHP version: 7.1.9
- API Framework: ThinkPHP 5.0

```
$jwt = JWT::encode($token, $privateKey, 'RS256');
$decoded_before_expired = JWT::decode($jwt, $publicKey, array('RS256'));
```

But when I try to use RS512 publicKey/privateKey in the example without any changes in the code, it just run as perfect as with the RS256 keys of the example **which means I still use the `RS256` mode to encode and decode my jwt!**

And when I try to use `RS512` mode in the example code like this:

```
$jwt = JWT::encode($token, $privateKey, 'RS512');
$decoded_before_expired = JWT::decode($jwt, $publicKey, array('RS512'));
```

The php framework just told me:

```
DomainException in JWT.php line 201
OpenSSL unable to sign data

        }
        list($function, $algorithm) = static::$supported_algs[$alg];
        switch($function) {
            case 'hash_hmac':
                return hash_hmac($algorithm, $msg, $key, true);
            case 'openssl':
                $signature = '';
                $success = openssl_sign($msg, $signature, $key, $algorithm);
                if (!$success) {
                    throw new DomainException("OpenSSL unable to sign data");
                } else {
                    return $signature;
                }
        }
    }

    /**
     * Verify a signature with the message, key and method. Not all methods
     * are symmetric, so we must have a separate verify and sign method.

```

**All fine in the `RS256` mode, did I misunderstand something here?**

**Comment by ronaldroe** [comment]
I'm having the same issue 4 years later. It's been 4 years, no help, no fixes, still open. That error message tells me exactly zero about why it's failing. I don't even know how to begin troubleshooting this.

For me, I get the error on RS256 and RS512. No other output.

**Comment by yash30201** [comment]
More reference may be taken from: https://dev.to/adhocore/minimalist-yet-powerful-php-jwt-library-2f5l

Closing as this seems answered.
