### ISSUE TITLE
Encoding JWTs adds escape slashes before base64 encoding

### ISSUE THREAD

**Issue by johnrhunt** [firebase/php-jwt#226]
So when you call the encode() method it uses the json_encode() function which by default escapes slashes - this isn't needed because the data is encoded anyway.

    vendor/firebase/php-jwt/src/JWT.php:304

    $json = json_encode($input);

The problem with doing this is that other services don't escape slashes and therefore if you're using this package to compare a signature it'll fail.

It would be worth using `JSON_UNESCAPED_SLASHES` in a new breaking version, or at least include the option to use `JSON_UNESCAPED_SLASHES` as an additional argument.

**Comment by bshaffer** [comment]
This library uses `JWT::jsonEncode` for everything, so this has long since been fixed.
