### ISSUE TITLE
Can we create multiple JWT's against one user?

### ISSUE THREAD

**Issue by Awais-cb** [firebase/php-jwt#231]
I have some questions

1. Can we create multiple tokens against one user if yes how? if no why?
2. lets consider a scenario where users wants to be logged in from mobile and web application too at the same what would happen?
3. what if user wants to logout how we are supposed to refresh/destroy/replace old token?

any help regarding would be really appreciated also it would be nice if i can a documentation about this library

**Comment by cottton** [comment]
1. You can create more than one JWT for one user. _Even for the same device (which would not make sense but ...)._

2. Each device gets its own JWT.
Example:
- User logged in via mobile (server creates and returns JWT)
- User logged in via web app (server creates and returns JWT)
- User requests via mobile using its JWT. Server validates JWT and sends response.
- User requests via web app using its JWT. Server validates JWT and sends response.

_Web apps actually could use another adapter like PHP session cookies. Imo you should add adapters anyway. One for JWT session, one for PHP session cookies, ..._

JWT is **not** like your passport.
The passport would be your login credentials.
Lets say the JWT is a bus ticket.
- You request one bus ticket with your passport.
- You request another bus ticket with your passport.
- You request a 3rd bus ticket with your passport.
Now you have 3 tickets (JWT). All 3 are valid until they expire _(do bus tickets expire?)_

_You of curse COULD set a limit by the server. F.e. 5 JWT per user id or 1 JWT per device. You then would have to store the JWT on the server. But thats not the point of JWT. JWT is meant to be stateless. They are signed and their content immutable. 
The server created the JWT using a private key. Clients can validate the JWT (signature) using the public key. If you change the token (content) then the signature does not fit and its no longer valid._

3. 
Logout: Same answer as posted here: https://github.com/firebase/php-jwt/issues/230
Refresh: client wants a new access token
- client sends refresh token
- server validate stored refresh token
- server removes the (now burned) refresh token
- server creates new refresh and access -token
- server returns both tokens
_A refresh token is for one time use only_

Destroy: Is a logout. 
Replace: ? Would be a refresh.

**Comment by NielsDom** [comment]
@cottton very good answer thanks
@Awais-cb you should close this issue

**Comment by Awais-cb** [comment]
yeah thanks cotton your answer is great

**Comment by Anurag-ravi** [comment]
Almost after a week struggling to get its answer, i finally got it from you
Thank you very much @cottton
