### ISSUE TITLE
Is this repo unmaintained?

### ISSUE THREAD

**Issue by DeepDiver1975** [firebase/php-jwt#232]
Hi,

it appears that this repo i unmaintained - pull requests are not reviewed and issues seem not to looked at ...

@bshaffer can you please comment on that?

Maybe it's time to fork .....

Thanks a lot!

**Comment by lindelius** [comment]
Yupp, it's pretty much abandoned. I ended up creating [my own library](https://github.com/lindelius/php-jwt) for this reason, which you're more than welcome to have a look at and even contribute to if you feel that something's missing.

**Comment by bshaffer** [comment]
This library is still maintained! We just added some pretty cool features (see) #256 and will release a new version soon.
