### ISSUE TITLE
access-token and refresh-token

### ISSUE THREAD

**Issue by riux** [firebase/php-jwt#233]
Hello I have my api rest in php and my client in vuejs, how should I implement and store the refresh-token and the access-toekn?

**Comment by cfv1000** [comment]
hello - depends on how you want to use the application.

You could use localStorage / sessionStorage to keep the tokens.
You could populate the storage data using interceptors or events.

You could even implement a retry policy if you want. 
Firebase doesn't really care how you handle the tokens. This library is used only to create the token.

Anything else is your decisions - make judgement calls. Just make sure you don't burn down the world :)

**Comment by wrabit** [comment]
Pretty much what that guy said ^

If your api and client are operating on the same domain, the most secure way is to store your token inside an HttpOnly cookie and use CSRF.

**Comment by ajupazhamayil** [comment]
Thank you for the discussion, closing this thread.
