### ISSUE TITLE
token解密的时候，遇到个问题不止怎么解决

### ISSUE THREAD

**Issue by luoyajiang** [firebase/php-jwt#240]
![image](https://user-images.githubusercontent.com/33601095/54515718-e4430e80-4997-11e9-81c3-c5b06484ee29.png)
我在进行token解密的时候，我不知道这个问题怎么解决？

**Comment by luoyajiang** [comment]
Simple and rude way, commented on this line of error

**Comment by xinhaonaner** [comment]
try catch 中捕获这个 \SignatureInvalidException错误

**Comment by lindelius** [comment]
@luoyajiang Please include the raw (base64 encoded) token that you are trying to decode, and I will have a look at it. I expect that there’s an encoding issue.
