### ISSUE TITLE
JWT::decode return null

### ISSUE THREAD

**Issue by raulbht** [firebase/php-jwt#241]
Good afternoon, I have a web page that is updated every 5 minutes and sends a token in each update to check if the token has not expired.

The problem is that when the current date and time in seconds is greater than the 'exp' of the token the function JWT :: decode returns null instead of returning the exception 'Token expired' having the function JWT :: decode inside a try catch.

Can somebody help me? Since I've been like this for a couple of days and I can not move forward ...

**Comment by cottton** [comment]
?
There is no try|catch at `JWT::decode()`
https://github.com/firebase/php-jwt/blob/master/src/JWT.php#L134
If you call `JWT::decode()` and use a try block around then its up to you.

**Comment by bshaffer** [comment]
I agree with @cotton that this is not possible. You can provide a leeway if you think this is a race condition:

```php
$jwt = new JWT();
$jwt::$leeway = 1;
```

If you're getting null as a return value from `JWT::decode` then I'm guessing someone modified the code of the package in your installation.
