### ISSUE TITLE
Invalid signature encoding

### ISSUE THREAD

**Issue by luoyajiang** [firebase/php-jwt#242]
![image](https://user-images.githubusercontent.com/33601095/56873937-b4902780-6a68-11e9-8c87-faffe893770d.png)

Why is that? Please help! Thank you

**Comment by luoyajiang** [comment]
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJMb2dpbk5hbWUiOiJYSUFPWVUuTEkiLCJQYXNzd29yZCI6IjEiLCJjdXJyZW50VGltZSI6MTU1NjUwMDM4MSwiZXhwaXJlcyI6MjU5MjAwLCJjb250cm9sbGVyIjoiY3JlZGl0X2FwcGx5X25vcm1hbFwvaW5kZXgiLCJhaWQiOiIzMDEzNDQzIiwiaWQiOiIxMjMyMDg5IiwiZmlkIjoiMTMiLCJmbG93TmFtZSI6Ilx1NWUzOFx1ODljNFx1NGZlMVx1NzUyOFx1OTg5ZFx1NWVhNlx1NzUzM1x1OGJmNyIsImFjdGl2ZU1lc3NhZ2UiOiJcdThiZjdcdTViNTBcdTUxNmNcdTUzZjhcdTRmZTFcdTc1MjhcdTdlYzRcdTViYTFcdTYyNzkifQ.FaBOczDJq-PKecEbSk3qckXCGn6ZVaNZqyCdzkZkz1Mxsbcxy


![image](https://user-images.githubusercontent.com/33601095/56873970-f9b45980-6a68-11e9-87fb-a6b30dfea158.png)

public_key   is     'email_approval_key'  ,This is this.

**Comment by lindelius** [comment]
I suspect that there’s an encoding issue at play here... and unfortunately it’s present in my own library, as well. I will have a look at it.

**Comment by zilahir** [comment]
hey guys! any update on this? i am having the same issue, can't sign my token. Any idea how to fix this?

**Comment by lindelius** [comment]
@zilahir Can you please include some token data to debug with and I'll check it out
