### ISSUE TITLE
SignatureInvalidException when request has formData

### ISSUE THREAD

**Issue by vahidvdn** [firebase/php-jwt#245]
When I want to upload a file with javascript, I get `SignatureInvalidException`. With simple request, this doesn't happen. I use formData in my upload request which adds some `Content-Type` to the request automatically.

**Comment by vahidvdn** [comment]
Actually, this happens in a very specific case. I use Codeigniter. This works in a controller function but gives me the error in `MY_Controller`.

I'm not sure this error relates to this plugin or the Codeigniter framework.

**Comment by Krisell** [comment]
Look at the JWT raw data and compare them for the two different cases. You probably have some problem with encoding that i not resolved before you try to decode the JWT.

**Comment by ajupazhamayil** [comment]
Sorry about the very late reply here. I hope Looking at raw data and comparing them helped you on this issue. If not, Could you please explain a bit on the `My_Controller` or steps to reproduce this issue?
