### ISSUE TITLE
Is this project no longer maintained?

### ISSUE THREAD

**Issue by inhere** [firebase/php-jwt#247]
Is this project no longer maintained? :(

**Comment by bajinho** [comment]
Good Question.

**Comment by brenc** [comment]
Doesn't look like it is. I switched to https://github.com/adhocore/php-jwt quite a while ago myself and haven't had any issues with it.

**Comment by bshaffer** [comment]
This library is still being maintained! Sorry for the lack of response. We plan on releasing a new version very soon (with some cool features like https://github.com/firebase/php-jwt/pull/256)
