### ISSUE TITLE
Can't decrypt a generated token

### ISSUE THREAD

**Issue by smalldragoon** [firebase/php-jwt#258]
Hi, 
I guess I'm missing somehting very basic here. I tried URL64 decode/encode ..Etc.. with my token but I'm still unable to get it properly. When I use JWT.io, token is decrypted without any problem.
Where am I missing something in the code below ? reading doc , I don't need to do anything else than this ? ( error is 

>  Uncaught exception 'Firebase\JWT\SignatureInvalidException' with message 'Signature verification failed' 

Thx in advance

```
<?php
require __DIR__ . '/vendor/autoload.php';

use \Firebase\JWT\JWT;
$jwt = "eyJraWQiOiJUUyIsImFsZyI6IkhTMjU2In0.eyJzdWIiOiJsaW9uZWwiLCJvcCI6ImF1dGgiLCJsdmwiOjEsImRzaWQiOiJhZTk0ZjdiOC03YzliLTRlYWUtOTZhNy04ZjAxZWEwNTQxOTEiLCJpc3MiOiJUUyIsInBpZCI6ImxvZ2luIiwicGFyYW1zIjp7fSwic2lkIjoiODFhNmVmNWYtZjhhZi00ODk4LWIyZmUtYWM1OTBhZDQyYWEzIiwiYXVkIjoid2ViYXBwIiwicHZpZCI6InN0YXRpYyIsImV4cCI6MTU3MzAzNjUxMCwiaWF0IjoxNTczMDM0NzEwLCJqdGkiOiIzMmM4Y2YxZi0wYTE3LTQ3ZTUtOWVhNi05ZTRlZDlhZTQ4NTAiLCJkaWQiOiIxZTdjMDQwZC01ZGM5LTRlMzktYjBjYy0wMjUwZTI4ZjY0MDQifQ.KU9dpKENm1_YmBngCEnXP2XiGpCkA7sf5pmojB7TzKM";
$key = "secret";


print_r("JWT\n\n");
print_r($jwt);

$decoded = JWT::decode($jwt, $key, array('HS256'));
echo "DECODED\n";
print_r($decoded);


?>

```

**Comment by RayHughes** [comment]
Im having issues with this as well. Sometimes it works, some times it doesn't. Im switching to a different library tho.

**Comment by Krisell** [comment]
Your token is fine and consists of the three parts HEADER.PAYLOAD.SIGNATURE. Base64-decoding works fine on the header and payload, but the signature doesn't match for the key you provided, so I'm guessing the real key is not "secret"?

Note that the content is not encrypted, that is not the purpose of JWT signatures, hence JWT.io, and anyone else, can read the data just fine without the signature secret.

Note also that this JWT was not generated using this package (as seen in the header) but it should still validate if you use the right secret.

**Comment by Krisell** [comment]
> Im having issues with this as well. Sometimes it works, some times it doesn't. Im switching to a different library as this one hasn't been updated since 2017.
> 
> `PHP 7.3`

Can you provide some examples? The algoritm is completely deterministic and it sounds very weird that it would work sometimes and sometimes not.

**Comment by danielwoestman** [comment]
Did you guys figure this out? I'm having the same issue. I'm trying to authenticate a google user via google assistant and need to get the email of the user. I know "secret" is not the right $key and I don't seem to be able to get the info without a valid $key value like I can in jwt.io

**Comment by Krisell** [comment]
@danielwoestman The key has nothing to do with seeing the data, but only to verify the signature. The data is not encrypted and can be read (and altered) by anyone. See the specification: https://jwt.io/introduction/ and the short version is that you need to split on the two periods (.), and then Base64Url decode the middle item. But this is of course completely insecure and you should not trust the data without verification.

**Comment by danielwoestman** [comment]
@Krisell Thanks, that was actually super helpful. 

Using this library, if I'm trying to verify using use Google's public keys (available in [JWK](https://www.googleapis.com/oauth2/v3/certs) or [PEM](https://www.googleapis.com/oauth2/v1/certs) format) to verify the token's signature, I'm confused at what to put in for the $key variable. I'm not sure how to get [Google's explanation](https://developers.google.com/assistant/identity/google-sign-in) to fit into this.

**Comment by bshaffer** [comment]
This library supports PEM format only, currently. There are ways to convert JWK to PEM if necessary, but with thee public keys you have supplied, using the PEM version will work as expected.
