### ISSUE TITLE
Error parsing AWS ALB Public Key

### ISSUE THREAD

**Issue by jalalomary** [firebase/php-jwt#265]
I am trying to using AWS OIDC. The returned token uses ES256 for signing the JWT. openssl_verify is throwing the error:

```
error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag
error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error
```

Sample public key returned from AWS:

```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE4eAWXhEm8pu66JIWu3KjA3OO/ymg
4PsTYB94LgTf2hU2sjKABqg01iHTh5kWSlyQ5iOwQim0FDrER5EuAt0F8A==
-----END PUBLIC KEY-----
```
Any clue of the root cause of this error?

**Comment by jalalomary** [comment]
Was able to resolve it using this commit: https://github.com/firebase/php-jwt/pull/256/commits

**Comment by bshaffer** [comment]
Yes, sorry we are trying to tag a new version but are currently encountering issues with Packagist permissions. Hopefully we'll have a new release soon!
