### ISSUE TITLE
Tag Update

### ISSUE THREAD

**Issue by lucidlemon** [firebase/php-jwt#269]
Could we get the latest commits to be v5? They are already merged but composer still pulls the old version from 2017 if we try to install it.

**Comment by bshaffer** [comment]
I have already emailed packagist.org, unfortunately the original maintainers have left and forgot to give me access to tagging the packagist repo. Sorry for the inconvenience!

**Comment by bshaffer** [comment]
In the meantime you can get the current codebase by running `composer require firebase/php-jwt:dev-master`

**Comment by bshaffer** [comment]
This has been tagged! Please update to `firebase/php-jwt:^5.1`
