### ISSUE TITLE
JWT::encode PHP doc declaration incompatibility

### ISSUE THREAD

**Issue by phil-davis** [firebase/php-jwt#279]
`JWT::encode` has `$payload` documented as:
```
     * @param object|array  $payload    PHP object or array
```
But unit tests have calls like:
```
        $msg = JWT::encode('abc', 'my_key');
```
which is passing a string as the payload. (I guess a string is "an array of bytes")

My IDE shouts about this. Should the PHP doc include `string` ?

**Comment by bshaffer** [comment]
There is no way to to pass a string and receive a valid JSON payload. In practice, the payload must be an array or object, otherwise the resulting JSON will not be an object.

Those tests do not use legitimate data, because they are for testing. Sorry for the confusion.
