### ISSUE TITLE
Add "sub" (subject) claim validation

### ISSUE THREAD

**Issue by MichielDeMey** [firebase/php-jwt#28]
As defined in the [JWT Draft, Section 4.1.2](https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#section-4.1.2) you can add a subject as a claim.

Subjects are [`StringOrURI`](https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#section-2), which means that it can either contain a string value or an [RFC 3986](https://tools.ietf.org/html/rfc3986) URI.

However, this PHP library does not support validating this claim yet.
Are you working on getting this in the library?

I assume it would be as simple as checking the subject of a token and compare it with an array of whitelisted subjects.

**Comment by robertdimarco** [comment]
@MichielDeMey Thanks for the report - I'll handle this.

**Comment by bshaffer** [comment]
Closing this issue because it's quite old, and we haven't received any asks for it... probably because applications can check this manually very easily.
