### ISSUE TITLE
Base64 Decrypt

### ISSUE THREAD

**Issue by maltboy** [firebase/php-jwt#281]
Why can the generated token be decrypted by Base64? What should I do?

**Comment by Krisell** [comment]
JWT is not an encryption protocol. It's meant for signing information which provides integrity, but not confidentiality. See the specification here: https://tools.ietf.org/html/rfc7519

**Comment by maltboy** [comment]
> JWT不是加密协议。它用于签名提供完整性但不提供机密性的信息。请参阅此处的规范：[https](https://tools.ietf.org/html/rfc7519) : [//tools.ietf.org/html/rfc7519](https://tools.ietf.org/html/rfc7519)
> 
> Base64只是用于JWT的编码。请注意，“编码”和“加密”是两个完全不同的主题。
> 
> 当然，您可以在将数据嵌入到JWT中之前对其进行加密。

**Comment by maltboy** [comment]
Thanks for your answer
