### ISSUE TITLE
Add EC Support in JWK.php

### ISSUE THREAD

**Issue by bshaffer** [firebase/php-jwt#286]
See 0c693a40a80a88d7eb06960205b24c820e8a04e0

**Comment by MikeBeas** [comment]
Would love to see this added, too. If I knew how I’d do it myself but crypto is a bit behind me at this point!

**Comment by DCdeBrabander** [comment]
I need this. Anyone know of an alternative? some simple dropin just for EC key types?

**Comment by bshaffer** [comment]
Closing in favor of #339

**Comment by bshaffer** [comment]
This is now available to try out for `EC256`. Please see https://github.com/firebase/php-jwt/pull/399!
