### ISSUE TITLE
Failed to login using JWT from Firebase

### ISSUE THREAD

**Issue by leossmith** [firebase/php-jwt#287]
I am working on a PHP Slim 4 API, which should use the token coming from Firebase authentication to access the api. However I keep getting this error in my logs no matter what:

`OpenSSL error: error:0906D06C:PEM routines:PEM_read_bio:no start line [" TOKEN_FROM_FIREBASE "]`

and this is the response to my GET:

```
{
    "statusCode": 500,
    "error": {
        "type": "SERVER_ERROR",
        "description": "ERROR: openssl_verify(): supplied key param cannot be coerced into a public key on line 243 in file E:\\xampp\\htdocs\\playground\\my-api\\vendor\\firebase\\php-jwt\\src\\JWT.php."
    }
}
```
Any ideas?

Thanks

**Comment by leossmith** [comment]
In further digging, I found out that if I replace the line 243: $success = openssl_verify($msg, $signature, $key, $algorithm); with $success = 1; everything works as expected. Looks like the library can't process the public keys from Google?

**Comment by leossmith** [comment]
Ok after a lot of try and error, it looks like the library takes care of splitting the keys in Kids Array and pKeysArray so I dont have to. After feeding it with the keys directly it worked.

**Comment by dennis-berg** [comment]
What exactly does "takes care of splitting the keys in Kids Array and pKeysArray so I dont have to" mean? @leossmith

**Comment by dennis-berg** [comment]
Do I have to supply the kid in the header and supply the array of keys with that kid as arraykey of key to fix this error?
