### ISSUE TITLE
Error Message: Key may not be Empty

### ISSUE THREAD

**Issue by AhmedKhan64** [firebase/php-jwt#288]
Hi, I am trying to run a project with docker but no matter what I do it is giving this error message.
{
    "message": "Key may not be empty",
    "url": "/api/threads/unread.json?companyId=171",
    "code": 500,
    "file": "/var/www/cake3-app/vendor/firebase/php-jwt/src/JWT.php",
    "line": 79
}
What can I do to solve the error?

**Comment by bishhop5** [comment]
This error message is usually caused when you haven't set your JWT **secret** / key when encoding your JWT token 
ie:

`$token = JWT::encode($payload, JWT_SECRET)`

so when your decode, you need to pass the secret, e.g:

`JWT::decode($token, JWT_SECRET, ['HS256']`

**Comment by qusade-dev** [comment]
i can do this on local but when i try it on server it's not work. i have set my JWT, but it still give me message "Key may not be empty"
