### ISSUE TITLE
When expire

### ISSUE THREAD

**Issue by alexroitman** [firebase/php-jwt#290]
Hi,first of all, sorry about my english.
Anyone have an implementation of this code on an API?
I am coding an REST API in php with CodeIgniter 4 and i don't know if this token expire in a while (with some config)or if is always the same token for the same input.

**Comment by Repox** [comment]
Unless specifically set, the generated token does not expire.

You need to add the [registered claim](https://tools.ietf.org/html/rfc7519#section-4.1.4) `exp` to your token, in order for this library to invalidate the usage of the token:

```php
<?php
use \Firebase\JWT\JWT;

$key = "example_key";
$payload = array(
    "iss" => "http://example.org",
    "aud" => "http://example.com",
    "iat" => 1356999524,
    "nbf" => 1357000000,
    "exp" => time() + (60 * 60), //Expire the JWT after one hour from now
);

$jwt = JWT::encode($payload, $key);
```

Now, if you try and reuse the the produced token after an hour, you will get an `ExpiredException`:

```php
<?php
use \Firebase\JWT\JWT;

$key = "example_key";

try {
$decoded = JWT::decode($jwt, $key, array('HS256'));

} catch ( \Firebase\JWT\ExpiredException $exception ) {
    // Tell the user that their JWT has expired
}
```

Hope that helps.

**Comment by phpcodingmaster** [comment]
Would be a good idea to add this to the main page to the example that shows the payload.
