### ISSUE TITLE
Payload is inaccessible in Expired / BeforeValid scenarios

### ISSUE THREAD

**Issue by bendoh** [firebase/php-jwt#291]
Though the JWT is cryptographically valid in scenarios where it is being accessed chronologically out of bounds, callers have no easy way of seeing the payload that _would_ be considered valid otherwise.

It would be useful to attach the "would-be" payload to thrown exceptions `BeforeValidException` and `ExpiredException`, so then callers would still be able to check the claims therein and act on them knowing that they are still invalid to some degree.

**Comment by Krisell** [comment]
What would the use case be for that?

The specification (https://tools.ietf.org/html/rfc7519#section-4.1.4) states that `The "exp" (expiration time) claim identifies the expiration time on
   or after which the JWT MUST NOT be accepted for processing.` One could argue that decoding the data is "processing", thus not complying with the standard.

**Comment by lindelius** [comment]
Monitoring.

**Comment by bendoh** [comment]
So my use case is, "this user gave me a token, I know it's a valid token, but it's either expired or before its time: what are its claims anyway?"

I'd say "MUST NOT be accepted for processing" is compatible with this idea: the token is not _accepted_ (the exception is still thrown,) but I do know that it was/will be valid: what claims did it make?

One pretty obvious use case: The user's token expired, and I want to know which user that is.

Attaching the payload to the thrown exception would make it easier to find out, rather than having to decode the JWT parts again in the application layer.

**Comment by Marshal313** [comment]
I have patched and created a [Pull request](https://github.com/firebase/php-jwt/pull/292) for this

**Comment by OssiPesonen** [comment]
I have a similar use-case for this need. 

We receive the token as a means of identifying a user when he closes a chat on one of our applications. The token gets stored by the chat when he opens the chat and by the time he closes it, it might have expired. We can't read the users verified information due to the expiration, which should be ignored at that point as we do not return any data from our API, we just store information.

**Comment by bendoh** [comment]
@OssiPesonen  I'd be very wary of adding extra arguments, _especially_ boolean arguments, since they really cause the method to mean two different things, and so it should be written as two different methods instead, e.g., `decode` and `decodeIgnoringExceptions`, but just attaching the payload to the exception avoids this weirdness and IMO is more correct since indeed it is an error condition.

**Comment by OssiPesonen** [comment]
I would argue that the name `decode()` means that you should be returned with the payload of a decoded token. The function  should not be responsible in reading the payload and throwing exceptions if it is expired, but leave that option for the user to do with it as he pleases, or have some mechanism to enable/disable it on a use-case basis.

In any case as this does not seem to be progressing (1.5 months) we might fork the library and continue development in-house.

**Comment by Marshal313** [comment]
> In any case as this does not seem to be progressing (1.5 months) we might fork the library and continue development in-house.

I'm using [My own fork](https://github.com/Marshal313/php-jwt) in which I fixed this issue.
You can fork that and continue from there

**Comment by ajupazhamayil** [comment]
I see the PR https://github.com/firebase/php-jwt/pull/521 has merged to resolve this issue. Hence closing it. Thank you for raising this issue!
