### ISSUE TITLE
Update to php 7.2

### ISSUE THREAD

**Issue by OriginersMc** [firebase/php-jwt#294]
Hi

Can you update this library to php 7.2 or height please?

Best regards

**Comment by Krisell** [comment]
The package works great on 7.2 or higher.

**Comment by OriginersMc** [comment]
I have the next files and function mcrypt_get_block_size() no work on php 7.4.2
[jwt.zip](https://github.com/firebase/php-jwt/files/4615658/jwt.zip)

**Comment by Krisell** [comment]
That function is deprecated since php 7.1. I can't see that it's used anywhere in this library – please show us where.

**Comment by Krisell** [comment]
After looking at your zip-file, it seems like you are using the deprecated function in your code. You need to update this, and that is not part of this library.

**Comment by OriginersMc** [comment]
Can you help me update this?, I can pay you for this task.

**Comment by Krisell** [comment]
Sorry, no. All I can say is that you should not use DES as you did in the zip file, that has been insecure for many years.

**Comment by Pointotech** [comment]
This seems like a ticket worth closing.

**Comment by JimTools** [comment]
I still think the core of this issue can be actioned, Upgrading the library to use PHP 7.4 as versions below this are no longer supported.

[PHP Supported Versions](https://www.php.net/supported-versions.php)
