### ISSUE TITLE
Leeway customization

### ISSUE THREAD

**Issue by caswell-wc** [firebase/php-jwt#298]
I am having an issue where my server's clocks are a little bit off from the server that is creating my jwt token. This is causing my jwt to not validate because the nbf is set and the server thinks that it is before the time that the nbf is set to. I noticed that there is a leeway static property that is supposed to compensate for that but it is set to 0 by default. How am I supposed to adjust that property if it is a static property?

**Comment by Krisell** [comment]
You should be able to set it using `JWT::$leeway = 60;` (or whatever value you want). `static` means it's accessible on the class and not on an instance. It does not mean that it's unchangeable.

**Comment by caswell-wc** [comment]
Thank you, that did solve my issue. I guess I've never had a need to change a static value before so I didn't think you could.
