### ISSUE TITLE
Get result as array instead of Stdclass option

### ISSUE THREAD

**Issue by minutephp** [firebase/php-jwt#30]
Hi,

Thanks for this nice little and useful class. I have just one issue.. Right now the JWT class returns StdClass object instead of a simple array.

I was wondering if we can please have the option to return the object as array as well? Maybe as an option.

It would be great because some functions like array_merge, etc **don't** support StdClass and make life a bit harder. All that's needed to be done is something like this:

```
json_decode($input, **true**) inside the jsonDecode function I guess?
```

Please think about it.

Thanks,
san

P.S. I know we can just **typecast** the object to (array) but that does not recursively work for nested arrays. The objects inside still remain of StdClass :'(

**Comment by ADmad** [comment]
`$array = json_decode(json_encode($stdClass), true)` Viola you have an array!

**Comment by lcabral37** [comment]
as descrived in the README is not the intended behavior?
    $decoded_array = (array) $decoded;

**Comment by minutephp** [comment]
I know we can just *typecast* the object to (array) but that does not
recursively work for nested arrays. The objects inside still remain of
StdClass :'(

**Comment by srcspider** [comment]
:+1: 

It's quite a waste to have to json encode/decode to get the right result.

I understand that it might make sense in other languages to return a class, but its honestly just a giant pain when it come to PHP to have to work with the useless `stdclass` broken pattern. `stdclass` is functionally just an array that's incompatible with any of the usual array functions, ie. just harder to use for no benefit; it's a complete anti-pattern to please java developers that have no clue what they're doing.

-

Proposed simple change: add a extra marameter `$assoc` that specifies associative or non-associative (default it to `false`, for backwards compatibility but also so its the same as `json_decode`). The internal `JWS::jsonDecode` would be switched to always output arrays and the logic would also be switched to array syntax (its probably too troublesome to support both simultaneously). On output would then just cast to object if the assoc parameter is false, ie. `(object) $payload` (this will result in a `stdclass`)

Simple, backwards compatible, easy to implement.

*If supporting both is a problem, then arrays should be the one that's supported, not `stdclass`.*

**Comment by prodigeris** [comment]
This is causing me a great pain. I'd love to see a feature that lets me to decode it as an array.
`stdclass` is a `std`

**Comment by bshaffer** [comment]
You can cast a stdclass as an array easily in PHP:

```sh
php > $stdc = new StdClass;
php > $stdc->foo = 'bar';
php > var_dump((array) $stdc);
php shell code:1:
array(1) {
  'foo' =>
  string(3) "bar"
}
```

**Comment by NiMeDia** [comment]
@bshaffer before just closing this one could you please at least read the conversation -> braindead casting will not work for nestet objects. It will cause bugs in the wild and it would be good if the project itself would handle the casting properly and well tested. It would be nice if you instead just accept the pull request (including tests) which was done with care by another user of this project. Thanks a lot...

**Comment by bshaffer** [comment]
@NiMeDia you can cast any nested `stdClass` as an array in the same way.

In the next major release of this library we will use `array` instead of `stdClass`.

**Comment by NiMeDia** [comment]
@bshaffer indeed you can manually go trough a nested structure and cast everything to anything, but is this really the thing you want to do after every decode call, if you could simply rely on a nested array structure.

+1 for using arrays in the future.
