### ISSUE TITLE
Why leading slashes in use statements of sc/JWT.php

### ISSUE THREAD

**Issue by kewlashu** [firebase/php-jwt#300]
[PHP documentation ](https://www.php.net/manual/en/language.namespaces.importing.php) mentions that leading back slash is not required in `namespace` `use` statements.

Is there any reason in file `src/JWT.php` line 5 to 8 have leading backslash in `use` statements

**Comment by Krisell** [comment]
It's probably added by mistake. Please make a PR, removing these and showing that the tests still pass.

**Comment by kewlashu** [comment]
Ok, I will create a PR
