### ISSUE TITLE
InvalidArgumentException needs use statement in JWK.php

### ISSUE THREAD

**Issue by pendenga** [firebase/php-jwt#302]
If JWK throws an InvalidArgumentException I get an error "Class 'Firebase\JWT\InvalidArgumentException' not found". This can be resolved by adding this to the top of JWK.php:

`use InvalidArgumentException;`

**Comment by akkivarma10** [comment]
Hi, any update on when this fix is going to be released ? @bshaffer

**Comment by CsabaBecskei** [comment]
Hi @bshaffer,
I'm also waiting for this to be merged https://github.com/firebase/php-jwt/pull/303

**Comment by bshaffer** [comment]
Thanks for the summons! I'll merge and tag this right away.
