### ISSUE TITLE
Getting "Invalid IAP credentials: Jwt payload is invalid" error with IAP enabled

### ISSUE THREAD

**Issue by san3jaya** [firebase/php-jwt#306]
I am getting this error on google cloud and I've enabled the IAP. this one is working perfectly on local.

`Invalid IAP credentials: Jwt payload is invalid [Line 0, column 7: No quote found for string field] for payload {"sub":1,"iss":"caters","iat":1602225351,"exp":1602225851,"locale":"en_EN","language":"en_EN"}`

**Comment by Krisell** [comment]
According to the spec, the `"sub"`value must be a `StringOrURI`, i.e. it needs to be quoted, as the error message says.

**Comment by yash30201** [comment]
Closing as this seems solved.
