### ISSUE TITLE
Why token is insecure?

### ISSUE THREAD

**Issue by iranapporg** [firebase/php-jwt#309]
Hi
Tokens that I make it, is secure and the hacker can decode it in many site
But I need to secure it
For example, you can decode token here [http://calebb.net/](url)
Can I do it?

**Comment by Krisell** [comment]
JWT tokens are by default not encrypted, and are not intended to provide confidentiality – the data is stored completely in cleartext. What they do provide is integrity via the signature, i.e. they can't be tampered with and their validity can be verified.

There are versions of JWT that add encryption, if that is what you want, or you can simply encrypt the data before you put it into a JWT. Please see the specification here: https://tools.ietf.org/html/rfc7519

**Comment by omid-student** [comment]
> 
> 
> JWT tokens are by default not encrypted, and are not intended to provide confidentiality – the data is stored completely in cleartext. What they do provide is integrity via the signature, i.e. they can't be tampered with and their validity can be verified.
> 
> There are versions of JWT that add encryption, if that is what you want, or you can simply encrypt the data before you put it into a JWT. Please see the specification here: https://tools.ietf.org/html/rfc7519

Yes you right
Thank you

**Comment by bshaffer** [comment]
If you'd like to ensure the payload is encrypted, you can look at the [JWE specification](https://datatracker.ietf.org/doc/html/rfc7516). This library and JWT (as mentioned above) do not support encrypted payloads.
