### ISSUE TITLE
Replicating claims as headers is deprecated and will removed from v4.0

### ISSUE THREAD

**Issue by sahakavatar** [firebase/php-jwt#315]
"Replicating claims as headers is deprecated and will removed from v4.0. Please manually set the header if you need it replicated."
what is this and how can I fix it ?

**Comment by drjoju** [comment]
At this moment the only solution I found is to downgrade the library p

"lcobucci/jwt": "3.3.0"

In composer.json

I found the solution here.

https://stackoverflow.com/questions/65004207/laravel-passport-7-5-1-replicating-claims

**Comment by nehamcs** [comment]
update composer to "lcobucci/jwt:3.3.3" this

**Comment by dmytro-skelia** [comment]
I had the same issue with Laravel upgrade 5.5->5.6. We don't have `lcobucci/jwt` in out composer.json and composer desided by itself to use 3.4.* because symfony has a depency on it. I had to specify explicitly "lcobucci/jwt:3.3.3" in composer.json as it was recommended above.

**Comment by irvine48** [comment]
`- kreait/firebase-tokens 1.15.0 requires lcobucci/jwt ^3.4.1|^4.0 -> found lcobucci/jwt[3.4.1, ..., 3.4.x-dev, 4.0.0-alpha1, ..., 4.2.x-dev] but it conflicts with your root composer.json require (3.3.3).`

how to change change it to 3.3.3?

**Comment by bshaffer** [comment]
This refers to a different repository - we are not `lcobucci/jwt`. I am closing this issue because it is not actionable in this repostiory.
