### ISSUE TITLE
How can I use a private key with a passphrase?

### ISSUE THREAD

**Issue by JorgeSivil** [firebase/php-jwt#318]
The encode() method accepts only the key, but there's no way to pass a passphrase.

Is it possible to use?

**Comment by mooreds** [comment]
From looking at https://github.com/firebase/php-jwt/blob/master/src/JWT.php it looks like the signing uses https://www.php.net/manual/en/function.openssl-sign.php which doesn't appear to handle a passphrase.

**Comment by drupol** [comment]
> From looking at https://github.com/firebase/php-jwt/blob/master/src/JWT.php it looks like the signing uses https://www.php.net/manual/en/function.openssl-sign.php which doesn't appear to handle a passphrase.

That's not true.

Actually, `openssl_sign()` needs a private key `priv_key_id` which can be either in a string or a resource.

If you want to use a private key with a passphrase, you just need to use:

```php
$pKeyId = openssl_pkey_get_private('/path/to/private.pem'); // Resource
$bool = openssl_sign($data, $signature, $pKeyId);
openssl_free_key($pKeyId);
```

**Comment by michael-bouvy** [comment]
Took me some time but eventually figured out how to achieve this:

```php
$res = openssl_pkey_get_private(
  '-----BEGIN ENCRYPTED PRIVATE KEY----- .... -----END ENCRYPTED PRIVATE KEY-----',
  'passphrase'
);

$jwt = JWT::encode($payload, $res, 'RS256');
```

Although `encode` method's signature states that `key` param should be a string, it works perfectly fine passing a key resource, which is eventually passed to `openssl_sign` function, accepting such resource as `private_key` param.

**Comment by bshaffer** [comment]
Thanks @michael-bouvy! We should update the phpdoc and README to show this!

**Comment by michael-bouvy** [comment]
I'll create a PR quickly.

**Comment by bshaffer** [comment]
@michael-bouvy I created one here! 

https://github.com/firebase/php-jwt/pull/335
