### ISSUE TITLE
critical vulnerability

### ISSUE THREAD

**Issue by iamjochem** [firebase/php-jwt#32]
hi there,

you might not be aware yet, but a critical vulnerability has been found and published in your JWT lib, see the following links:

https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
http://jwt.io/

**Comment by flyon** [comment]
+1 came here to say the same

**Comment by sarciszewski** [comment]
I sent #33 to fix it.

**Comment by robertdimarco** [comment]
#33 Merged to address this issue.

**Comment by robertdimarco** [comment]
A few add'l changes forthcoming.

**Comment by robertdimarco** [comment]
See #35 - deploy forthcoming.
