### ISSUE TITLE
Allow for claim validation to be set optionally

### ISSUE THREAD

**Issue by zcmack** [firebase/php-jwt#325]
According to the ietf spec [jwt ietf spec](https://tools.ietf.org/html/rfc7519#section-4.1) the `nbf`, `iat` and `exp` claims are OPTIONAL. 

The library should allow for skipping these claims in addition to setting an acceptable leeway value.

**Comment by Krisell** [comment]
Aren't they already implemented as optional in this library? You can simply skip adding them to the payload.
When decoding, they are checked if they are present in the JWT, that should not be optional, right?

Also, the leeway can be set via the public static proprerty.

**Comment by zcmack** [comment]
i think that implies coupling between client and server. i, as the validator of tokens would like to decide if i am going to validate the claims within, whether or not a given client includes said claims in the token. not a big deal if you don't want to introduce this, i can switch libraries. this would have just saved me some time. 😀

**Comment by lindelius** [comment]
Just out of curiosity, how does this cause a problem? @zcmack

**Comment by zcmack** [comment]
my particular issue is with `iat` and is related to time drift on some client nodes running in data centers that i don't control. i know i can configure leeway to adjust for this but with the level of inconsistency i'm seeing (sometimes validation occurs "before" issued, sometimes "after"), setting an arbitrarily large leeway and having it apply to all claims feels a bit heavy handed compared to skipping just the `iat` claim. its a simple enough fix to manage in a fork but figured i may as well open an issue and see if there was interest in a PR.

**Comment by lindelius** [comment]
Thanks for sharing your use case :)

I would say that there are 2 "real" solutions to that problem, however, I do understand that neither might be an option for you at this time. I am going to list them here anyways, though, in case they might be alternatives for someone else:
- Fix (or at least minimize) the clock skew and then set a reasonable leeway time, if still needed
- Stop including the `iat`, `nbf`, and `exp`, claims when issuing the JWTs

That said, I don't think it's an unreasonable feature to be able to selectively validate (or not validate) claims, and I will definitely keep that in mind for future development of my library (not this one). Unfortunately, I can't fix that for you right away (or even promise that it will for sure be implemented at all). Not sure if there is a library that doesn't automatically validate these claims for you (haven't tried all of them), but check the ones on [JWT.io](https://jwt.io) if you haven't already.
