### ISSUE TITLE
Error em shared web server

### ISSUE THREAD

**Issue by igoluciano** [firebase/php-jwt#349]
Friends, I'm using JWT right on my local machine with codeigniter 4 and then when I send my application to a shared web server it works in parts, like, I register a new user, get the token from the database and when I do some action with the token that gives me authorization to continue the same returns me status 401 .... can someone help me?

**Comment by Krisell** [comment]
This is not a support forum. What you are describing does not sound like a problem with this JWT package, but rather with your application or Codeigniter. I suggest you try to seek help from a support channel instead.

If you still think there is a bug in this package, you need to describe the problem in much more detail and provide steps to reproduce this in a minimal example.

**Comment by ajupazhamayil** [comment]
Closing this inactive issue. Thank you for the discussion.
