### ISSUE TITLE
Cannot handle token prior to (time) error - How to resolve

### ISSUE THREAD

**Issue by Andiyanga** [firebase/php-jwt#350]

**Comment by Andiyanga** [comment]
I tried to decode a generated jwt with _**JWT::decode()**_ method. It threw an error message which reads "_Cannot handle token prior to 2021-07-30T02:16:20+0100_". I have tried to resolve the error by using _**JWT::$leeway**_ but it does not work. How may I resolve the error?
Thanks!

**Comment by cottton** [comment]
"Prior" - so your token is valid in future.

See https://github.com/firebase/php-jwt/blob/master/src/JWT.php#L132


> How may I resolve the error?

Do not create tokens with a date (nbf (not before)) in the future?
Or use a larger leeway, which makes no sense to me, but ... . _The leeway applies to exp (expire) date too._

**Comment by chae-useb** [comment]
You can set the issue date of JWT to the time prior to current time. 
eg.  $issue_date = time() - 30; // your jwt is issued 30 second before now.

I guess JWT::$leeway = 30 is the same
