### ISSUE TITLE
Refresh token example

### ISSUE THREAD

**Issue by dimityrivanov** [firebase/php-jwt#355]
Is there any example with working with refresh token and issuing new access token ?

**Comment by Krisell** [comment]
The JWT standard does not have any concept of a "refresh token" or "access token".

You're probably referring to OAuth or some other standard, so you are more likely to find examples in places related to that rather than here.

**Comment by dimityrivanov** [comment]
Whats the expected behaviour to do after token expiration on mobile device without loggin out the user ?

**Comment by cottton** [comment]
Working code, no. Wrong place.
Examples|discussions about refresh token: https://github.com/firebase/php-jwt/issues/119#issuecomment-525464922
