### ISSUE TITLE
How can I catch the jwt token if its coming from external server

### ISSUE THREAD

**Issue by Yusufjon** [firebase/php-jwt#356]
In my case JWT tokens are coming from Wix bookings. I have given the url and with ngrok I am able to see the POST request with JWT tokens. I need to catch it and decode. However, currently I couldnt catch it. If anybody had the same experaince pls help me

**Comment by mixones-open** [comment]
> In my case JWT tokens are coming from Wix bookings. I have given the url and with ngrok I am able to see the POST request with JWT tokens. I need to catch it and decode. However, currently I couldnt catch it. If anybody had the same experaince pls help me

You can put the token parameter in the url or in the header, and then get the submitted parameters in the framework or parse the information in the header.

**Comment by Krisell** [comment]
Your question doesn't make much sense (what does `catch it` mean, `$_POST['token']`?), and is definitely not related to an issue in this project. You are more likely to get help with this in basic web development forums.
