### ISSUE TITLE
Support for JWE generation?

### ISSUE THREAD

**Issue by Tigatok** [firebase/php-jwt#359]
Hi there,

I am trying to take this implementation, using JOSE, and see if I can use this php-jwt library to create a token in the similar fashion:

                var jweToken = JWT.Encode(payload, jweKey, JweAlgorithm.DIR, JweEncryption.A128CBC_HS256);

I'm trying to get the JweAlgorithm.DIR set up. Does php-jwt support this? I looked at source code but not sure if I've missed something.

**Comment by bshaffer** [comment]
I am not really sure what you're asking, and this issue is very old, so I'm closing this. If this is still relevant, feel free to open a new issue with more detail. Thank you.
