### ISSUE TITLE
Header kid resolved in null

### ISSUE THREAD

**Issue by tomerBZ** [firebase/php-jwt#380]
https://github.com/firebase/php-jwt/blob/83b609028194aa042ea33b5af2d41a7427de80e6/src/JWT.php#L113

Hi guys,

If keys with $header->kid  = "0"/0 this will be resolved as null duo to PHP nature:
```
echo empty("0") // 1
echo empty(0) // 1
```

**Comment by bshaffer** [comment]
Good catch. We could swap this out for `property_exists` instead.

```php
property_exists($header, 'kid') ? $header->kid : null 
```
