### ISSUE TITLE
I am facing  "Signature verification failed" with ssl domain on live 

### ISSUE THREAD

**Issue by GurupriyaWebvillee** [firebase/php-jwt#390]
An uncaught Exception was encountered
Type: UnexpectedValueException

Message: Signature verification failed

Filename: /home/seryapp/public_html/application/helpers/jwt_helper.php

Line Number: 63

Backtrace:

File: /home/seryapp/public_html/application/helpers/authorization_helper.php
Line: 20
Function: decode

File: /home/seryapp/p

**Comment by bshaffer** [comment]
This appears to be WAD as the keys you are using failed to verify against the signature. 

If you're using SHA or RSA, this means `openssl_verify` returned `0`. If you're using EdDSA, this means `sodium_crypto_sign_verify_detached` returned `false`. If you're using HMAC, this means your HMAC hashes did not match.
