### ISSUE TITLE
Decode returns this errors  Uncaught UnexpectedValueException: $keyOrKeyArray must be an instance of Firebase\JWT\Key key or an array of Firebase\JWT\Key

### ISSUE THREAD

**Issue by ashigue** [firebase/php-jwt#396]
Hi,

I'm using decode function like this but get this error
$token = Firebase\JWT\JWT::decode($jwt, 'MY_SECRET_KEY');

------
Error
------
Fatal error</b>:  Uncaught UnexpectedValueException: $keyOrKeyArray must be an instance of Firebase\JWT\Key key or an array of Firebase\JWT\Key keys in /home/user/public_html/Project/api/vendor/firebase/php-jwt/src/JWT.php:416
Stack trace:
#0 /home/emanrpdk/public_html/Acash/api/vendor/firebase/php-jwt/src/JWT.php(114): Firebase\JWT\JWT::getKey('EnDieuResideLaL...', NULL)
#1 /home/user/public_html/Project/api/checkDocIfGiven.php(32): Firebase\JWT\JWT::decode('eyJ0eXAiOiJKV1Q...', 'XXXXXXXXXXXX...')
#2 {main}
  thrown in <b>/home/user/public_html/Project/api/vendor/firebase/php-jwt/src/JWT.php</b> on line <b>416</b><br />

Need help please.

**Comment by ashigue** [comment]
found the solution

**Comment by sushant-nehe** [comment]
Hey @ashigue ,
I'm calling the decode function like this `JWT::decode($jwt, $secret_Key, ['HS512'])` and facing the same issue that you were facing, I have already spend almost 2 days on this issue but still did not find anything to solve.
Can you please share your solution, It'll be grateful.
Thanks in advance.

**Comment by ashigue** [comment]
> Hey @ashigue ,
> I'm calling the decode function like this `JWT::decode($jwt, $secret_Key, ['HS512'])` and facing the same issue that you were facing, I have already spend almost 2 days on this issue but still did not find anything to solve.
> Can you please share your solution, It'll be grateful.
> Thanks in advance.

add this on top
use Firebase\JWT\Key;

and use JWT::decode($jwt, new Key(JWT_SECRET_KEY, 'HS512')); instead of JWT::decode($jwt, $secret_Key, ['HS512'])

**Comment by waldirborbajr** [comment]
Hi, I'm facing same error... I've downloaded latest release unzip it, cause, I don't use compose.

And I receive the error message that "Uncaught Error: Class Firebase\JWT\Key not found"

// required to decode jwt
require_once '../config/core.php';
require_once '../libs/jwt/src/BeforeValidException.php';
require_once '../libs/jwt/src/ExpiredException.php';
require_once '../libs/jwt/src/SignatureInvalidException.php';
require_once '../libs/jwt/src/JWT.php';
require_once '../libs/jwt/src/JWK.php';
use Firebase\JWT\JWT;
use Firebase\JWT\Key;


      // decode jwt
      $decoded = JWT::decode($jwt, new Key($privateKey, 'HS256'));
