### ISSUE TITLE
'Signature verification failed' on JWT::decode

### ISSUE THREAD

**Issue by Nixon-Joseph** [firebase/php-jwt#409]
Same question marked on SO here: https://stackoverflow.com/questions/71355758/firebase-jwt-php-signature-verification-failed-on-jwtdecode

composer says I'm on version `6.0.0`

Here's my code generating the token:
``` php
public static function GenerateNewAuthTokens(User $user): string {
    $issuedAt   = new DateTimeImmutable();
    $expire     = $issuedAt->modify('+' . AuthenticationHelper::AUTH_EXPIRE_MINUTES . ' minutes');
    $username   = $user->Username;
    $issuedAtTimestamp = $issuedAt->getTimestamp();

    $auth_data = [
        'iat'  => $issuedAtTimestamp,                // Issued at: time when the token was generated
        'iss'  => AuthenticationHelper::SERVER_NAME, // Issuer
        'nbf'  => $issuedAtTimestamp,                // Not before
        'exp'  => $expire->getTimestamp(),                           // Expire
        'userName' => $username,                     // User name
    ];

    return JWT::encode(
        $auth_data,
        AuthenticationHelper::SECRET_KEY,
        AuthenticationHelper::ALGORITHM
    );
}
```

Here is my code attempting to decode the token:
```php
public static function GetAuthData(): ?object {
    $headers = getallheaders();
    if (isset($headers) && count($headers) && isset($headers['Authorization']) && strlen($headers['Authorization']) > 7) {
        try {
            $token = explode(" ", $headers['Authorization'])[1];
            $decodedToken = JWT::decode($token, new Key(AuthenticationHelper::SECRET_KEY, AuthenticationHelper::ALGORITHM));
            return $decodedToken;
        } catch (\Throwable $th) {
            //TODO
            $err = $th;
        }
    }
    return null;
}
```

It throws the "Signature verification failed" error in the JWT code [here][1].

So far as I can tell - I'm following the example given on the [repo home screen][2] to a reasonable approximation.

I am using `HS512` but have tried `HS256` as well with no difference.

I have confirmed that the token I'm attempting to decode is exactly what was generated in the first method.

It's failing the compare check [here][3], due to `$hash` and `$signature` not matching.

  [1]: https://github.com/firebase/php-jwt/blob/92aa12d73dfbf4ee157cf4d01c5342869dcd9d56/src/JWT.php#L130
  [2]: https://github.com/firebase/php-jwt
  [3]: https://github.com/firebase/php-jwt/blob/92aa12d73dfbf4ee157cf4d01c5342869dcd9d56/src/JWT.php#L312

**Comment by Nixon-Joseph** [comment]
So turns out I wasn't sending the exact same token back that I was receiving. When JWT encodes the token data, it trims off the `=` at the end of any of the base64 encoded strings. What I had stored contains those `=` at the end (usually). Because of this, when it ran its compare - it failed.

In summary - dur - check the values better.

**Comment by Nixon-Joseph** [comment]
Did you read my closing comment where my token didn't match 100%? And are you 100% sure yours matches completely?

If you're sure of the above, and still are having issues, then I'm sorry. From what I can tell this library works exactly as intended, there's likely something going on with the parameters provided. If not, then good luck!

**Comment by kulahin** [comment]
Also ensure, that token stored for your user has been created using exactly the same key as you use for decoding. My case: I logged in using some generated with some key (let's say, key=aaa111), then realized that my key is incorrect and changed key to the different one (let's say, key=bbb222). But that first key (aaa111) has been stored for my user and decoding kept failing again and again :)
