### ISSUE TITLE
Auth, login and logout

### ISSUE THREAD

**Issue by Maykonn** [firebase/php-jwt#41]
Please, add a better documentation, how to auth an user, make a login and logout with php-jwt. Cause not found nowhere in the web.

**Comment by robertdimarco** [comment]
@Maykonn This library is not intended as a general purpose authentication framework. It is just one component of a broader authentication story - and fulfills the narrow purpose of minting and decoding / verifying JSON Web Tokens. Specifically, I'd like to avoid adding any "recipes" for this library that would suggest a fully secure system without full knowledge of what JWTs are, how they should be used, etc.
