### ISSUE TITLE
Sign In With not working

### ISSUE THREAD

**Issue by PabloManuel78** [firebase/php-jwt#410]
I'm having trouble implementing this solution from Google. I'm doing it popup, not redirect.:
https://developers.google.com/identity/gsi/web/guides/overview

Everything from Javascript works fine. Everything works, the problem comes when I want to check the response (credential) from the server side:

![image](https://user-images.githubusercontent.com/5701864/157012248-09f8a059-a956-4f04-935f-7668962144c0.png)

This is the code that displays the access button. I have followed the instructions in detail.

`
		<div id="g_id_onload"
			data-client_id="<?=$clientID?>"
			data-callback="onSignIn"
			data-auto_prompt="false"
			data-context="use">
		</div>
		
		<div class="g_id_signin"
			data-type="standard"
			data-size="large"
			data-theme="outline"
			data-text="sign_in_with"
			data-shape="rectangular"
			data-logo_alignment="left">
		</div>	  
`

This is the custom function that handles the response.

`

		function onSignIn(response)
		{
			let credential = response.credential;

			if(response.credential)
			{
				data= {
					credential: response.credential
				};

				$.ajax({
					cache: false,
					type: "post",
					url: "/procesosajax.php?proceso=login_google",
					data: data,
					beforeSend: function(){
						$("body").append ('<div class="espera"></div>');
					},				    
					success: function(data)
					{
						$(".espera").remove();
						console.log(data);
					}
				})
			}
		}

`

And this is the server side code that fails.:

`

if ($proceso == "login_google")
{
	// authenticate code from Google OAuth Flow
	if (isset($_POST['credential'])) 
	{
		$credential	= ov("credential", 2, 2, 256, 2, 0);	

		require_once __RAIZ . '/lib/google-api-php-client--PHP8.0/vendor/autoload.php';

		// init configuration
		$clientID 		= '84**************-*****************************.apps.googleusercontent.com';
		$clientSecret 	= 'GOCSPX-**************************D5rK6K1GA';

		$client = new Google_Client();
		$client->setClientId($clientID);
		$client->setClientSecret($clientSecret);

		$payload = $client->verifyIdToken($credential);

		if ($payload) 
		{
			$userid = $payload['sub'];
			// If request specified a G Suite domain:
			//$domain = $payload['hd'];

			echo "login ok";
		} 
		else 
		{
			echo "Invalid ID token";
		}

	}
}

`

And this is the error.

`
<b>Fatal error</b>:  Uncaught UnexpectedValueException: Wrong number of segments: 2 in /var/www/vhosts/pruebasphp.com/httpdocs/lib/google-api-php-client--PHP8.0/vendor/firebase/php-jwt/src/JWT.php:92
Stack trace:
#0 /var/www/vhosts/pruebasphp.com/httpdocs/lib/google-api-php-client--PHP8.0/src/AccessToken/Verify.php(106): Firebase\JWT\JWT::decode()
#1 /var/www/vhosts/pruebasphp.com/httpdocs/lib/google-api-php-client--PHP8.0/src/Client.php(813): Google\AccessToken\Verify-&gt;verifyIdToken()
#2 /var/www/vhosts/pruebasphp.com/httpdocs/procesosajax.php(1013): Google\Client-&gt;verifyIdToken()
#3 {main}
  thrown in <b>/var/www/vhosts/pruebasphp.com/httpdocs/lib/google-api-php-client--PHP8.0/vendor/firebase/php-jwt/src/JWT.php</b> on line <b>92</b><br />

`

**Comment by PabloManuel78** [comment]
![image](https://user-images.githubusercontent.com/5701864/157013223-cf37c913-33cd-4733-ae10-e55af379b9de.png)
Only PHP8.0 side fails

**Comment by Krisell** [comment]
Whatever you're passing to `verifyIdToken` is not a JWT. Check your value of `$credential` before that.

Also note that this is not a support forum, but I'm sure there are other help channels for Google Sign In.

**Comment by PabloManuel78** [comment]
Correct, the chain was being adulterated.
