### ISSUE TITLE
Unexpected 'int'  expecting function  or const

### ISSUE THREAD

**Issue by vikrantgujjar** [firebase/php-jwt#411]
i am getting this error -

*"syntax error, unexpected 'int' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)"*

on line 40 File JWT.php
`public static int $leeway = 0;`

any help ?

**Comment by Krisell** [comment]
Typed properties was introduced in PHP 7.4, and version 6 of `php-jwt` even requires PHP 8. You or obviously on a lower version, and should be using version 5. I'm a bit confused how you ended up on version 6, Composer should install the latest compatible version.

**Comment by vikrantgujjar** [comment]
thank you @Krisell for quick reply, I have PHP 8 on my local pc and 7.2 on server. Due to restrictive internet access on server I can not update PHP version on server neither can install composer.
