### ISSUE TITLE
JWT decode failed due to server time difference 

### ISSUE THREAD

**Issue by lcabral37** [firebase/php-jwt#42]
I noticed there was a minor difference on the server generating the JWT and the server decoding it (on an openid connect project) and although the difference is within millisecs, very often the iat verification failed so I had to read up at the documentation and verify there is some recommendation at least for the exp and the nbf. so I've considered adding a leeway time to all time verification.

Sources: 
http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#nbfDef
http://openid.net/specs/openid-connect-core-1_0.html#IDToken

I've create a  pull request https://github.com/firebase/php-jwt/pull/39 to resolve this issue a while back so I'm not sure if the workflow in this project is to see an issue first before heading for the push requests :)

**Comment by lcabral37** [comment]
created a new pull request after new approach  as discussed in the first pull request

**Comment by robertdimarco** [comment]
:+1: New release coming within 24 hours that will include your changes. Thanks again!

This issue addressed via the new `JWT::$leeway` option added in [#46 - Provide a leeway in verification of times to account for clock skew](https://github.com/firebase/php-jwt/pull/46). This will be released as `v2.1.0`.
