### ISSUE TITLE
Argument 1 passed to Firebase\JWT\JWT::encode() must be of the type array, string given, called in

### ISSUE THREAD

**Issue by prakashmuvi** [firebase/php-jwt#422]
Hi Support,
Sudden, We are facing the below issue in a server:-
Argument 1 passed to Firebase\JWT\JWT::encode() must be of the type array, string given, called in (/var/www/html/newstudio/vendor/firebase/php-jwt/src/JWT.php:184)

We are just using the below line:-
$payload={"user_id":"2608","email":"siapos@yopmail.com","studio_id":"9247","password":"siapos123"};
define('JWTKEY', 'xyz123!'); 
$muvi5_token=JWT::encode($payload,JWTKEY,'HS256');

**Comment by Krisell** [comment]
That doesn't look like valid php, but perhaps you left out some string quotes around the JSON string.

You need to pass a php array as the $payload, so either `json_decode($json, true)` that JSON string, or define it as an array, i.e. `['user_id' => 2608, 'email' => ...]`

**Comment by prakashmuvi** [comment]
Hi krisell,
Thanks for your reply.
**Previously, We are passing json object:-**
$payload = json_encode(['user_id' => $users[0]['id'], 'email' => $username, 'studio_id' => $users[0]['studio_id'], 'password' => $password]);
define('JWTKEY', 'xyz123!');
$muvi5_token=JWT::encode($payload,JWTKEY,'HS256');

**I have changed to array , Now it is working fine**
$payload =['user_id' => $users[0]['id'], 'email' => $username, 'studio_id' => $users[0]['studio_id'], 'password' => $password];
define('JWTKEY', 'xyz123!');
$muvi5_token=JWT::encode($payload,JWTKEY,'HS256');

**Note:-**
Our codebase is the same for multiple environments but in other environments, it is working fine to pass the object. Is it depending on the version of JWT?

**Comment by Krisell** [comment]
Yeah it seems like https://github.com/firebase/php-jwt/pull/385 recently added types to the parameter list, which causes php to enforce that at runtime (previously only the docblock specified the array type). I'm not sure why strings aren't supported, perhaps that is per the specification, but in any case you're avoiding the double-JSON-encoding by passing that array instead of the JSON string.

**Comment by Krisell** [comment]
On a completely separate note, it doesn't look too good putting a plaintext password in a JWT (that is probably passed around, might end up in logging, localStorage, cookies or similar places).

**Comment by prakashmuvi** [comment]
> Yeah it seems like #385 recently added types to the parameter list, which causes php to enforce that at runtime (previously only the docblock specified the array type). I'm not sure why strings aren't supported, perhaps that is per the specification, but in any case you're avoiding the double-JSON-encoding by passing that array instead of the JSON string.

Hi Krisell,
Thanks for your reply. I have checked in both servers having the JWT versions are the same (6.1.2) but the PHP versions are different.
1)7.2
2)7.0

**Comment by bshaffer** [comment]
This is working as designed. The JWT specifies that the payload is a key/value array, and not a string.
