### ISSUE TITLE
Uncaught Error: Class Firebase\JWT\Key not found

### ISSUE THREAD

**Issue by waldirborbajr** [firebase/php-jwt#425]
Hi, I'm facing error class not found ... I've downloaded latest release unzip it, cause, I don't use compose.

And I receive the error message that "Uncaught Error: Class Firebase\JWT\Key not found"

// required to decode jwt
require_once '../config/core.php';
require_once '../libs/jwt/src/BeforeValidException.php';
require_once '../libs/jwt/src/ExpiredException.php';
require_once '../libs/jwt/src/SignatureInvalidException.php';
require_once '../libs/jwt/src/JWT.php';
require_once '../libs/jwt/src/JWK.php';
use Firebase\JWT\JWT;
use Firebase\JWT\Key;

  // decode jwt
  $decoded = JWT::decode($jwt, new Key($privateKey, 'HS256'));

**Comment by Krisell** [comment]
I strongly recommend you to use composer and autoloading, but if you want to include it manually, you need to require the Key.php class as well.

**Comment by waldirborbajr** [comment]
Gee.. thank you @Krisell after 4 hours breaking head ... damm... thank you so much.
