### ISSUE TITLE
Semver?

### ISSUE THREAD

**Issue by icatalina** [firebase/php-jwt#427]
Hi! 

I'm trying to figure out what kind of versioning does this library follows.

I can't find any breaking change between 4 and 5 https://github.com/firebase/php-jwt/releases/tag/v5.0.0, but I can see breaking changes between 6.0.0 and 6.1.0 (Drop support for PHP 5.3, 5.4, 5.5, 5.6, and 7.0).

Can someone explain how are we meant to read version numbers?

**Comment by Krisell** [comment]
Dropping support for a php versions is not necessarily a breaking change. Using composer, older runtimes will install an older version of the library.

**Comment by icatalina** [comment]
hey @Krisell, thanks for your prompt response. You are right, my bad. I guess I'm not used to that kind of behaviour from other package managers 😅 

Do you happen to know what the breaking changes between 3 and 5 are? I'm trying to update the library but found no references anywhere in the changelog or the releases 😕

**Comment by Krisell** [comment]
> Do you happen to know what the breaking changes between 3 and 5 are? I'm trying to update the library but found no references anywhere in the changelog or the releases 😕

Sorry, don't know. Your best bet might be to write tests (if you don't already have those) against your usage of v3 and then update to v5/6.

**Comment by icatalina** [comment]
Yeah, that's the plan, was just curious if it was documented somewhere...

**Comment by tuupola** [comment]
With semver as as long as [the public API does not change](https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api) upgrading dependencies does **not** require major version pump. PHP is just a dependency. I too wish there was a CHANGELOG. In the meanwhile you could  try [comparing the code](https://github.com/firebase/php-jwt/compare/v3.0.0...v5.0.0) between 3.0.0 and 5.0.0-
