### ISSUE TITLE
Decoding example in docs is incorrect

### ISSUE THREAD

**Issue by edalzell** [firebase/php-jwt#430]
The docs say do this:

```
use Firebase\JWT\JWK;
use Firebase\JWT\JWT;

// Set of keys. The "keys" key is required. For example, the JSON response to
// this endpoint: https://www.gstatic.com/iap/verify/public_key-jwk
$jwks = ['keys' => []];

// JWK::parseKeySet($jwks) returns an associative array of **kid** to Firebase\JWT\Key
// objects. Pass this as the second parameter to JWT::decode.
JWT::decode($payload, JWK::parseKeySet($jwks));
```

But the keys returned by that endpoint cannot be decoded as they don't include RSA, which is the only supported type: https://flareapp.io/share/x5MQQYb5

What is the correct endpoint to get the keys?

**Comment by edalzell** [comment]
Looks like https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com is the correct endpoint

**Comment by bshaffer** [comment]
Decoding these keys are now supported in `6.3.0`
