### ISSUE TITLE
[BIC][Documentation] Upgrade from version ^5 to 6.0.0 missing doc for ::sign function

### ISSUE THREAD

**Issue by Shadowmad** [firebase/php-jwt#436]
Hello, 
I was just upgrading `firebase/php-jwt` from version 5.4.0 to 6.2.0 and was managing Backwards Compatibility Breaking Changes from this changelog https://github.com/firebase/php-jwt/releases/tag/v6.0.0. 
I ran local tests to make sure changes that I added worked, but I received following error: `ArgumentCountError : Too few arguments to function Firebase\JWT\JWT::sign(), 2 passed`

After some digging I noticed we are not passing algo parameter into `sign`, after some digging between versions I noticed `sign` function dropped default value of `HS256` for algo in `sign` function starting version 6.0.0

Can this be reflected in the docs or is it possible to return this default statement?

Thank you very much for your time and maintenance of this project ^_^

**Comment by bshaffer** [comment]
You're right! I missed this in the release notes! Thanks for pointing this out, I've updated the release to reflect the changes made to the `JWT::sign` method.
