### ISSUE TITLE
Missing `ArrayAccess` type in docblock for decode() method

### ISSUE THREAD

**Issue by ppaulis** [firebase/php-jwt#444]
`JWT::decode()` accepts an `ArrayAccess` as key set, but the docblock isn't complete.

This causes errors when running Static Analysis tools like PHPStan:
```Parameter #2 $keyOrKeyArray of static method Firebase\JWT\JWT::decode() expects array<string, Firebase\JWT\Key>|Firebase\JWT\Key, Firebase\JWT\CachedKeySet given.```

 The following PR fixes this problem:

https://github.com/firebase/php-jwt/pull/443

**Comment by ppaulis** [comment]
Hi!
Is there a chance, that this small fix here could be merged sometime..?

Thanks!
Pascal

**Comment by yash30201** [comment]
@ppaulis, closing this issue as the PR is merged.

Thanks for contributing!

**Comment by ppaulis** [comment]
Has been a pleasure. Thanks for the great work :+1:
