### ISSUE TITLE
How to get Header?

### ISSUE THREAD

**Issue by CuminLo** [firebase/php-jwt#448]
If the JWT decode function  checksum is successful, how can I get the header?

For example, I need to logger header to file.

**Comment by th3c0r** [comment]
Hello,
if I understand correctly what you want maybe you can see the code below.

```
use Firebase\JWT\JWT;

$key = "test-key";
$now = time();

$payload = [
	'iss' => 'https://example.com', //a string contain the name or id of the issuer can be domain
	'aud' => 'https://example.com',
	'user' => 'testuser',
	'iat' => $now,//the timestamp of token issuigin
	'nbf' => $now //the timestamp of the toke should start being considered valid
];

$head = [
	'extra-head-value' => 'test-head-value'
];

$jwt = JWT::encode($payload, $key, 'HS256', null, $head);

$tks = \explode('.', $jwt);
if (\count($tks) !== 3) {
	throw new \UnexpectedValueException();
}

$headerRaw = JWT::urlsafeB64Decode($tks[0]);
$header = json_decode($headerRaw, true);

print_r($header);

```

**Comment by saranshdhingra** [comment]
Thanks for the solution @th3c0r 
Anyone accessing this issue can use the solution suggested in the comments.

I have also added a PR #501 to add this as a helper.

**Comment by bshaffer** [comment]
We do not want to add a utility function to decode headers because this could encourage our users to decode insecure headers (this happens before any validation occurs). To exclude these helpers is an intentional decision. Additionally, if users want to check their headers (insecurely), they can do so easily:

```php
list($headersB64, $payloadB64, $sig) = explode('.', $jwt);
$headers = json_decode(base64_decode($headersB64), true);
```
