### ISSUE TITLE
How to verify a JWT with several possible key in v6?

### ISSUE THREAD

**Issue by chennien** [firebase/php-jwt#464]
According to [[issue #214]](https://github.com/firebase/php-jwt/issues/214#issuecomment-564559753), JWT::decode accepted an array of several possible keys before v6, like this.
**$possible_keys = [
 'kid1' => 'my_key1', 
 'kid2' => 'my_key2',
];
$decoded = JWT::decode( $jwt, $possible_keys, ['RS256'] );**

May I know how can I achieve the same goal with the new key object in v6?
**$decoded = JWT::decode( $jwt, new Key($possible_keys, "RS256") );**

I got an error "_Fatal error: Uncaught TypeError: Firebase\JWT\JWT::getKey(): Return value must be of type Firebase\JWT\Key, string returned_" when I ran above code. 

Thank you.

**Comment by danilopolani** [comment]
The new signature of the `decode` method is:

```php
@param Key|array<string,Key> $keyOrKeyArray
```

So you can fix that by mapping the array to `kid => new key()`:

```php
use Firebase\JWT\Key;

$keys = [
    'kid1' => 'key1',
    'kid2' => 'key2',
];

JWT::decode($jwt, array_map(fn (string $key) => new Key($key, 'ALG HERE')));
```

@bshaffer maybe we can document this in the README and the [release notes of v6](https://github.com/firebase/php-jwt/releases/tag/v6.0.0)?

**Comment by chabid492** [comment]
thanks brother @danilopolani I have also facing this issue. solved with your solution
