### ISSUE TITLE
Please allow overriding alg and typ headers

### ISSUE THREAD

**Issue by mroux** [firebase/php-jwt#472]
Why would you prevent overriding those headers? They're already set by default, developers should have the option to override them.
Especially the "typ" one, what would be the point of that header if it always had to be "JWT"?

PR: https://github.com/firebase/php-jwt/pull/473

**Comment by bshaffer** [comment]
Thank you for your contribution. What is the reason you need to override "typ" and "alg"?

**Comment by ajupazhamayil** [comment]
No reply from the user, Closing this for now. Please feel free to open a new bug if it need further discussion.

**Comment by bshaffer** [comment]
The `"typ"` header is now able to be overwritten using the `$head` parameter as of [v6.10.0](https://github.com/firebase/php-jwt/releases/tag/v6.10.0). Note that supplying `"alg"` in the `$head` parameter will still not have an effect, as the required `$alg` parameter takes precedence.
