### ISSUE TITLE
Doesn't seem to work with random secret key on a WordPress Plugin

### ISSUE THREAD

**Issue by SoulPancake** [firebase/php-jwt#487]
I have tried to use php-jwt with multiple methods but none of the methods is supporting the secret key as a dynamically generated random string in my wordpress plugins

And the reason I can't keep a secret key is that the APIs I'm trying to authorize are on the plugin level and there are no environment variables for wordpress plugins at the plugin level.
How do we achieve this using FireBase JWT

**Comment by bshaffer** [comment]
I am not understanding your question / problem. Could you provide some more concrete examples of what you're trying to accomplish? 

This library is for encoding / decoding / verifying JWTs. It should work with random secret key as long as both sides (encode and decode side) have access to the secret key.

**Comment by SoulPancake** [comment]
Back when I was facing this problem
I was using a simple encode and decode and a privately stored variable for a wordpress plugin ( which was a randomly generated string ) as a secret key for the authentication
However, It always seemed to fail.

**Comment by bshaffer** [comment]
I am closing this issue as I do not think you are properly using the library. Please open a new one with more information if you still believe this is an issue.
