### ISSUE TITLE
How to catch an exception?

### ISSUE THREAD

**Issue by Chimit** [firebase/php-jwt#50]
I'm trying to use this package with Laravel, but I can't catch an exception. How to do that correctly?

```php
public function render($request, Exception $e)
{
    if ($e instanceof DomainException) {
        return 'Caught!';
    }

    return parent::render($request, $e);
}
```

**Comment by xerardoo** [comment]
@Chimit  hi, how do you catch an exception?
I tried something like this, but didn't works. :(

`try{`
`$decoded = JWT::decode($token, $key, array('HS256'));`
`}catch(Exception $e){`
 echo 'Exception message '.$e ;
`}`

**Comment by lcabral37** [comment]
Try \Exception

What does the error message being dumped?

**Comment by xerardoo** [comment]
@lcabral37  Hi, I Tried `\Exception` and didn't work.

the error was 'Fatal Error : Classs'Firebase\JWT\SignatureInvalidException' ', I want to catch the error because is an api rest.

**Comment by Klerith** [comment]
So sad to see this issue after two years with no answers :/

I have the same issue.

**Comment by ijsucceed** [comment]
Thanks, @Klerith , it worked for me.
