### ISSUE TITLE
Cannot handle token prior to...

### ISSUE THREAD

**Issue by Hesesses** [firebase/php-jwt#51]
I'm getting errors like this sometimes:
```
Cannot handle token prior to 2015-06-04T06:05:30+0000
```
The error happens at the same time as the time above.

Why this happens and what I need to do to fix this?

**Comment by drtriumph** [comment]
You probably have a slight skew between the clock on the server that mints the tokens and the clock on the server that's validating the token - if the `iat` or `nbf` is in the future, then the token isn't yet valid.
One solution would be to use a small leeway, like this:
```php
JWT::$leeway = 5; // Allows a 5 second tolerance on timing checks
```

**Comment by motin** [comment]
Thanks for the solution! I ran into this locally using boot2docker and it's vm clock was far askew. To fix:

     boot2docker ssh sudo ntpclient -s -h pool.ntp.org
