### ISSUE TITLE
Add name space

### ISSUE THREAD

**Issue by CbrandVendini** [firebase/php-jwt#52]
When using a library such as this in a larger framework its very nice to have a properly namespaced file. Could I suggest that you namespace under your Git name:
namespace Firebase;
would be adequate and would insure that there would be no confusion between this library and anything using it that might out of necessity share its name.

**Comment by tuupola** [comment]
It can happen with only major version number bump. Changing current namespace would break bc.

**Comment by robertdimarco** [comment]
I'm not opposed to this, but as @tuupola it would require a major version bump. I'd be happy to look at a PR if anyone else feels strongly about this.

**Comment by jrjohnson** [comment]
:+1: for name spacing.

**Comment by Dashron** [comment]
Any opinions on what the namespace should be? I need to namespace this because I've run into a conflict with another library. I'll have a PR together today.

**Comment by CbrandVendini** [comment]
I think traditional namespacing these days on things that are pulled through composer is {githubuser}/{packagename} so it makes sense to use firebase/PHP_JWT

The package needs a version bump and namespacing, essential to keep moving forward.

**Comment by tuupola** [comment]
Composer package name is not the same as PHP namespace. For me namespace 'Firebase' would make sense. Classname can be as it is.

```php
namespace Firebase;
class JWT { ... }
```

This way you only need to add the following line and to make your old code work.

```php
use Firebase\JWT;
```

**Comment by Dashron** [comment]
With the addition of all of the exceptions we need two tiers. \Firebase\Exceptions would conflict with any other firebase php libraries.

I'm going to restructure the folders to match their other php library, https://github.com/firebase/firebase-token-generator-php

**Comment by robertvrabel** [comment]
@Dashron Is a new version going to be released so we can reference it when pulling it in via composer? I noticed the current v2.2.0 doesn't have this in it.

I'm currently referencing dev-master just to use this package, but would like to lock it to a version soon.

**Comment by robertdimarco** [comment]
@robertvrabel I'll cut a release today.

**Comment by robertdimarco** [comment]
Shipped as v3.0.0. Thanks everyone! :tada:
