### ISSUE TITLE
Version v6.6.0 seems to break compatibility with php 8.1 (maybe even php 8)

### ISSUE THREAD

**Issue by simonjamain** [firebase/php-jwt#522]
We just bumped our JWT version in [our project](https://gitlab.com/incubateur-territoires/france-relance/silab/silab-back/-/merge_requests/149) and we are getting `Error: Firebase\JWT\JWT::decode(): Argument #3 ($headers) cannot be passed by reference`.

[This "fix"](https://stackoverflow.com/questions/76468099/uncaught-error-firebase-jwt-jwtdecode-argument-3-headers-cannot-be-pas) does not do the trick for us so I am wondering  what php version you are using.
In [the official documentation ](https://www.php.net/manual/en/language.references.pass.php) I cannot find anything mentionning this technique (except for [this coment](https://www.php.net/manual/en/language.references.pass.php#128292)).

The exact version of php we are using is the one shipped with the [php:8.1-fpm](https://hub.docker.com/layers/library/php/8.1.0-fpm/images/sha256-001281a0eb6140b0e5096664d785abd6e6d2921316d002c1d912867725076299) docker image.

What I could fin out tho from [the breaking changes of php 7 to php 8](https://www.php.net/manual/en/migration80.incompatible.php) is this : 

> The compile time fatal error "Only variables can be passed by reference" has been delayed until runtime, and converted into an "Argument cannot be passed by reference" [Error](https://www.php.net/manual/en/class.error.php) exception.
> 
> Some "Only variables should be passed by reference" notices have been converted to "Argument cannot be passed by reference" exception.

I don't fully grasp every aspects of the changes they mention but they might be something there.

And I can also be completely in the wrong about this.

Thank you.

**Comment by Krisell** [comment]
Did you update from version 5 to 6 of `firebase/php-jwt`, and if so, did you follow the upgrade guide? https://github.com/firebase/php-jwt/releases/tag/v6.0.0

**Comment by wizhippo** [comment]
OIDC oauth2 league was the culprit for us.  They have a fix already but they have not yet tagged it.

**Comment by bshaffer** [comment]
Looks like the issue is that the league was passing in a third argument that didn't exist.  We added a third argument in the latest release (`v6.6.0`), which is backwards compatible, as the argument previously was not there. But since they were passing one anyway, this caused the issue.

For the time being, the solution is to downgrade to `6.5.0` until the league tags the fix mentioned above.
