### ISSUE TITLE
TypeError Key material must be a string, resource, or OpenSSLAsymmetricKey

### ISSUE THREAD

**Issue by syarifa20** [firebase/php-jwt#525]
TypeError
Key material must be a string, resource, or OpenSSLAsymmetricKey
FCPATH\vendor\firebase\php-jwt\src\Key.php at line 31

why when accessing API using jwt-php an error like this appears

**Comment by ilhammmaulana** [comment]
the key material must be a string, resource, or an OpenSSLAsymmetricKey object.

1. Verify the key material: Ensure that you are passing the correct key material to the jwt-php library. It should be a valid string, resource, or an OpenSSLAsymmetricKey object.

2. Check the key format: Ensure that the key material you are using is in the correct format. For example, if you are using a string-based key, make sure it is properly formatted and does not contain any unexpected characters.

3. Confirm the key type: Make sure you are using the appropriate key type for the specific functionality you are trying to achieve. For example, if you are signing a token, you might need a private key, whereas verifying a token may require a public key.

4. Validate dependencies: Check if you have the required dependencies installed and configured properly. Make sure you have the necessary OpenSSL extensions enabled in your PHP configuration.

5. Update the jwt-php library: If you are using an older version of the jwt-php library, consider updating it to the latest version. There might be bug fixes or improvements that can resolve the issue.

**Comment by bshaffer** [comment]
Thanks for the thorough response, @ilhammmaulana! 

@syarifa20 please read the above comment, and ensure you're passing in a string, resource, or OpenSSLAsymmetricKey as the first argument to `Firebase\Jwt\Key`.

If you are running into this error becasue you're upgrading from v5, see the [README examples](https://github.com/firebase/php-jwt#example) or the [v6.0 release notes](https://github.com/firebase/php-jwt/releases/tag/v6.0.0) for instructions on how to update your code to use the new `Key` classes.
