### ISSUE TITLE
Micorsoft Entra ID and msal-browser/2.37.1 error validation access token

### ISSUE THREAD

**Issue by Sampei4** [firebase/php-jwt#538]
Hi, I get the following error when I try to validate the access token:

`Firebase\JWT\SignatureInvalidException: Signature verification failed`

**Comment by bshaffer** [comment]
I am closing this issue as it does not contain enough information to debug the issue.

The exception you see is saying that the signature of the JWT does not match the public key you provided to validate it. This seems to be the library functioning as expected.

If you believe there is an error in this library, please provide data which proves that the library is not validating your token / public key correctly.
