### ISSUE TITLE
rate limit cache expiration is not working as expect in CachedKeySet.php

### ISSUE THREAD

**Issue by chris-lee-lb** [firebase/php-jwt#543]
This file  https://github.com/firebase/php-jwt/blob/main/src/CachedKeySet.php#L216 and this function `private function rateLimitExceeded(): bool`

1. `$cacheItem->expiresAfter(1); // # of calls are cached each minute`, but according to PSR 6 spec (https://www.php-fig.org/psr/psr-6/), `public function expiresAfter($time);` => `An integer parameter is understood to be the time in seconds`
2. `$this->cache->save($cacheItem);` looks like will overwrite ttl each time. So when ratelimit cache key exists, `$cacheItem->expiresAfter()` will not be executed, and lifetime will be overwritten to unlimited.

I thinks all two parts are not expect behaviors.

**Comment by bshaffer** [comment]
Hello @chris-lee-lb ! Thank you for filing this issue.

I see the problem in the first point, but in the second point, if you retrieve a cache item successfully (e.g. `isHit` is `true`), it shouldn't overwrite the TTL. I coded up a quick test to prove this (please tell me if I'm missing something):

```php
use Google\Auth\Cache\MemoryCacheItemPool;

$cache = new MemoryCacheItemPool();
$rateLimitCacheKey = 'foo123';

// This will never be a hit since this is an in-memory cache
$cacheItem = $cache->getItem($rateLimitCacheKey);
$cacheItem->expiresAfter(60); // # of calls are cached each minute
var_dump($cacheItem); // dump expiration
$callsPerMinute = (int) $cacheItem->get();
echo("Calls per minute: $callsPerMinute\n");

echo "\nSleep for 5 seconds...\n";
sleep(5);

// The claim is that this will overwrite expiresAfter above
$cacheItem->set(++$callsPerMinute);
$cache->save($cacheItem);

$cacheItem = $cache->getItem($rateLimitCacheKey);
var_dump($cacheItem); // dump expiration
$callsPerMinute = (int) $cacheItem->get();
echo("Calls per minute: $callsPerMinute\n");
```
This uses the in-memory cache defined in [`google/auth`](https://github.com/googleapis/google-auth-library-php), and outputs the following:

```sh
object(Google\Auth\Cache\TypedItem)#2 (3) {
  ["value":"Google\Auth\Cache\TypedItem":private]=>
  uninitialized(mixed)
  ["expiration":"Google\Auth\Cache\TypedItem":private]=>
  object(DateTime)#4 (3) {
    ["date"]=>
    string(26) "2023-12-01 16:48:07.631770"
    ["timezone_type"]=>
    int(3)
    ["timezone"]=>
    string(3) "UTC"
  }
  ["isHit":"Google\Auth\Cache\TypedItem":private]=>
  bool(false)
  ["key":"Google\Auth\Cache\TypedItem":private]=>
  string(6) "foo123"
}
Calls per minute: 0

Sleep for 5 seconds...
object(Google\Auth\Cache\TypedItem)#5 (4) {
  ["value":"Google\Auth\Cache\TypedItem":private]=>
  int(1)
  ["expiration":"Google\Auth\Cache\TypedItem":private]=>
  object(DateTime)#4 (3) {
    ["date"]=>
    string(26) "2023-12-01 16:48:07.631770"
    ["timezone_type"]=>
    int(3)
    ["timezone"]=>
    string(3) "UTC"
  }
  ["isHit":"Google\Auth\Cache\TypedItem":private]=>
  bool(true)
  ["key":"Google\Auth\Cache\TypedItem":private]=>
  string(6) "foo123"
}
Calls per minute: 1
```

As you can see, the cached expiration is the same in both cases (`2023-12-01 16:48:07.631770`), and the cached value is updated as expected.

**Comment by mattsax** [comment]
It seems like psr6 requires an expiration to be set each time you save an item:

> If a calling library asks for an item to be saved but does not specify an expiration time, or specifies a null expiration time or TTL, an Implementing Library MAY use a configured default duration. If no default duration has been set, the Implementing Library MUST interpret that as a request to cache the item forever, or for as long as the underlying implementation supports.

Also, it seems there is no way to get the expiration, I found this discussion which conclusion was to remove a `getExpiration()` method: https://groups.google.com/g/php-fig/c/vbG1DcchdjI/m/Y3b546PoCwAJ

**Comment by mihaileu** [comment]
I really need the https://github.com/firebase/php-jwt/pull/556 to be merged, I lost hours in debugging this issue that caused downtime for my app as it couldn't refresh the jwks due to rate limit and my clients failed to be marked as logged in.

**Comment by bshaffer** [comment]
@mihaileu we are sorry to hear this caused you and your customers difficulty. Please update your library to [v6.10.1](https://github.com/firebase/php-jwt/releases/tag/v6.10.1), and this should now be fixed.
