### ISSUE TITLE
composer.phar should not be in repo

### ISSUE THREAD

**Issue by kcivey** [firebase/php-jwt#56]
Presumably composer.phar was checked in accidentally in e0a75bfb6413f22092c99b70f310ccb2cca3efa5? It should be removed and added to .gitignore.

I noticed because my IDE found it and started complaining about duplicate class definitions for things like Symfony\Component\Console\Input\InputOption.

**Comment by robertdimarco** [comment]
Thanks for the note - fixed in 21498f7b9e433b37b3a8d18388ccc77ed6853703.
