### ISSUE TITLE
الرموز المميزه

### ISSUE THREAD

**Issue by NawaraTafa** [firebase/php-jwt#562]

**Comment by ajupazhamayil** [comment]
Closing this issue as it does not have the required information.

**Comment by NawaraTafa** [comment]
Good evening, can I have details about this Email?

في الخميس، ٢٥ أبريل، ٢٠٢٤ ١٠:٤٨ ص Ajumal ***@***.***> كتب:

**Comment by NawaraTafa** [comment]
Can I know what information information is required?

في الجمعة، ٢٦ أبريل، ٢٠٢٤ ٢:٣٢ ص Rovy Gobran ***@***.***> كتب:
