### ISSUE TITLE
Class "Firebase\JWT\Key" not found

### ISSUE THREAD

**Issue by jmaster03** [firebase/php-jwt#563]
I don't know exactly why it is showing me this. I've installed the package in the lastest version, I don't know what else to do, please help.

![image](https://github.com/firebase/php-jwt/assets/46202461/bcc85fc5-90c2-4927-aaa9-800fff521a5e)
![image](https://github.com/firebase/php-jwt/assets/46202461/347cdd53-8918-4223-86c2-185c0fa7120e)

**Comment by yash30201** [comment]
Hi @jmaster03 , 

You need to add the composer autoloader at the top of the file. For example:

Let's say composer.json lies in your your `$ROOT` directory and you script lies in `$ROOT/src`, then at the top of the file just below `<?php`:

```php
require_once __DIR__ . '/../vendor/autoload.php';
```
