### ISSUE TITLE
How about some documentation?

### ISSUE THREAD

**Issue by marcospgp** [firebase/php-jwt#58]
I feel this library could use some documentation, especially some mention that if the token verification fails, an exception will be thrown. Also an example of code where a try catch block is used to decode a token would help.

 Thanks!

**Comment by toddmcbrearty** [comment]
+1

**Comment by peterholcomb** [comment]
:+1:   Great library by the way, very helpful in my latest project

**Comment by Mrkisha** [comment]
+1

**Comment by dperjar** [comment]
I generally agree but if anyone really does need some examples etc the tests aren't a bad place to start: https://github.com/firebase/php-jwt/blob/master/tests/JWTTest.php

**Comment by rutwick** [comment]
+1

**Comment by spacebiscuit** [comment]
+5

**Comment by xerardoo** [comment]
+10

**Comment by sonicwong** [comment]
+1

**Comment by fireproofsocks** [comment]
+1 https://medium.com/@craftsmancoding/wtfm-dbbec02eb172#.nqpu6uivi

**Comment by ajupazhamayil** [comment]
I see exception handling example is added to the readme itself and the issue is really old. Closing this issue. Thank you for the discussion.
