### ISSUE TITLE
How to catch Expired token

### ISSUE THREAD

**Issue by shiroamada** [firebase/php-jwt#65]
I got this Fatal error: Uncaught exception 'Firebase\JWT\ExpiredException' with message 'Expired token' in
I try to run try and catch, but it still come out Fatal Error. 

```
try{
    $decoded = JWT::decode($jwt, $key, array('HS256'));
}catch(\Exception $e){
     echo 'Caught exception: ',  $e->getMessage(), "\n";
}
```

I am using PHP-5.4.36
How to catch this error?
Thanks!

**Comment by shiroamada** [comment]
try{
			
			$decoded = JWT::decode($jwt, $key, array('HS256'));
		}catch(\Firebase\JWT\ExpiredException $e){
			 echo 'Caught exception: ',  $e->getMessage(), "\n";
		}

Ok, i miss out the namespace. Sorry for it.

**Comment by lcabral37** [comment]
You should have been able to have caught it with the \Exception none the
less...

On Fri, Aug 21, 2015 at 9:42 AM, shiroamada <notifications@github.com>
wrote:

> try{
>
>         $decoded = JWT::decode($jwt, $key, array('HS256'));
>     }catch(\Firebase\JWT\ExpiredException $e){
>          echo 'Caught exception: ',  $e->getMessage(), "\n";
>     }
>
> Ok, i miss out the namespace. Sorry for it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firebase/php-jwt/issues/65#issuecomment-133316822>.
>



-- 
Luís Miguel Cabral
Address/Snail mail (I like postcards): Sofies GT 43, 0168 Oslo, Norway
Mobile: 004741755497 (Norway)

**Comment by shiroamada** [comment]
Nope. I can't use \Exception to catch it.
I got Fatal error: Uncaught exception 'Firebase\JWT\ExpiredException' with message 'Expired token'.
With the namespace \Firebase\JWT\ExpiredException  then I able to catch it.

**Comment by sadranyi** [comment]
\Exception works fine with me. if you are using composer and all dependencies are resolved properly it should work just fine

**Comment by Sandeep3005** [comment]
Solved the problem .. but now issue is that I am getting expired token no matter how many time I ran that script  -- error remain same -- Why token is not refreshing remain expired

**Comment by mikelehen** [comment]
Can you clarify how you know the jwt you are decoding is not expired?  (by default Firebase tokens expire after 60 minutes, so if you're testing with an old token, it'll likely be expired)

**Comment by Shiva1029** [comment]
> try {
>         $token = JWT::decode($jwt, $key, array('HS256'));
>     }
>     catch (\Firebase\JWT\ExpiredException $e) {
>         print "Error!: " . $e->getMessage() . "<br/>";
>         die();
>     }

**Comment by Shiva1029** [comment]
use \Firebase\JWT\JWT;

**Comment by yanpengfei** [comment]
use \Firebase\JWT\JWT;


try {
            $tokenArray = JWT::decode($token, SECURITY_KEY, array('HS256'));
        }
        catch (\Firebase\JWT\SignatureInvalidException $e) {
            print "Error!: " . $e->getMessage();
            die();
        }

**Comment by Klerith** [comment]
This works for me

```
try {
        JWT::$leeway = 60; // $leeway in seconds
        $data = JWT::decode($token, $key, array('HS256'));
        return $data;

    } catch (\Exception $e) {
        return FALSE;
    }
```

**Comment by yulinzhihou** [comment]
@Klerith  it's works for me too

**Comment by harshan89** [comment]
```
try { 
      $decodejwt = (array) JWT::decode($this->jwt, KEY, array('HS256'));
      $output['token'] = $decodejwt;
      $output['success'] = true;
      $output['code'] = 200;
} 
catch (\Firebase\JWT\ExpiredException $e) { 
      $output['success'] = false;
      $output['errors'][] = $e->errorMessage();
      $output['code'] = 401;
}
```

**Comment by mapkyca** [comment]
I'm running into this myself - `ExpiredException` is uncatchable by using either `\Firebase\JWT\ExpiredException` or `\Exception` 

Any solution? This is kind of critical to my code.
