### ISSUE TITLE
Does it support hhvm?

### ISSUE THREAD

**Issue by kiwo12345** [firebase/php-jwt#67]
Hello,

I wonder if it supports/works with hhvm?

Thanks,

**Comment by mtdavidson** [comment]
I've not tried it but its tested on Travis under HHVM last test ran passed see https://travis-ci.org/firebase/php-jwt/jobs/79335909

**Comment by robertdimarco** [comment]
@mtdavidson Thanks for posting that link to the test run! I haven't tried it either, but certainly open to reports / filing bugs if there is evidence of problems. Closing this out for now.
