### ISSUE TITLE
Add JWK support

### ISSUE THREAD

**Issue by fproject** [firebase/php-jwt#70]
Should we add JWK support?

**Comment by lcabral37** [comment]
That would be nice.
Not sure how often it comes to be needed but as our project required JWK to
validate the JWT I had to implement a JWKmanager.

I'm willing to contribute if needed.

On Mon, Sep 28, 2015 at 6:19 AM, F-Project Team <notifications@github.com>
wrote:

> Should we add JWK support?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firebase/php-jwt/issues/70>.
>



-- 
Luís Miguel Cabral
Address/Snail mail (I like postcards): Sofies GT 43, 0168 Oslo, Norway
Mobile: 004741755497 (Norway)

**Comment by diegoeduardorios** [comment]
any progress?

**Comment by kwallace-abvio** [comment]
rrdial, thank you for the pointer to fproject/php-jwt.  I'm working on a project that uses AWS Cognito and I was having trouble  converting the jwks.json supplied by AWS to PEM.  fproject/php-jwt works great for me in that it takes the jwks.json (all the keys), finds the right key, and converts it to PEM.  I'd prefer to use firebase/php-jwt but until it supports jwks I'll just use fproject/php-jwt.

**Comment by navasiloy** [comment]
> That would be nice.
> Not sure how often it comes to be needed but as our project required JWK to
> validate the JWT I had to implement a JWKmanager.
> 
> I'm willing to contribute if needed.
> 
> On Mon, Sep 28, 2015 at 6:19 AM, F-Project Team [notifications@github.com](mailto:notifications@github.com)
> wrote:
> 
> > Should we add JWK support?
> > —
> > Reply to this email directly or view it on GitHub
> > #70.
> 
> Luís Miguel Cabral
> Address/Snail mail (I like postcards): Sofies GT 43, 0168 Oslo, Norway
> Mobile: 004741755497 (Norway)

Nowadays that really needed. JWKs became a standart pushing from Auth0 team and other vendors.
@fproject Can you go ahead and create a corresponding PR? If you want I can do myself?

**Comment by ashishtilara** [comment]
any plans to get JWK support anytime soon :)

**Comment by viion** [comment]
Any updates? AWS Cognito uses jwks.

**Comment by aaronpk** [comment]
Would be awesome to get JWK support here! I'd rather use this library than the bigger spomky labs one.

**Comment by marioskamperis** [comment]
Do we have any news about possible jwk support?

**Comment by MikeBeas** [comment]
I’d also like to know if there’s any update on this… I am about to start work on a project requiring this and I have no way to handle the JWK right now. I would prefer not to have to change to a fork and require my team to install the other version to get it working.

**Comment by musa11971** [comment]
Apple also exposes [JWKs](https://appleid.apple.com/auth/keys) to verify their JWTs, so would really like to see this!

**Comment by marioskamperis** [comment]
+1 for the apple comment.
Now trying to implement Apple Sign-In and would really useful not to load any other libraries

**Comment by bshaffer** [comment]
Please test the code in `master` via composer and I can tag a new version once this feature has baked a bit:

```
composer require firebase/php-jwt:dev-master
```

**Comment by Einenlum** [comment]
For people looking for JWK support in late 2020, this is supported since [v5.2.0](https://github.com/firebase/php-jwt/releases/tag/v5.2.0)

**Comment by ssi-anik** [comment]
> For people looking for JWK support in late 2020, this is supported since [v5.2.0](https://github.com/firebase/php-jwt/releases/tag/v5.2.0)
> See [tests](https://github.com/firebase/php-jwt/blob/master/tests/JWKTest.php) for the implementation (no documentation yet).

If someone somehow reached here and looking for a quick solution by not going through the tests,
```
$jwks = [ 'keys' => []]; 
// set of keys, the keys key must have to be there. 
// for example, the response of this endpoint is a valid sample https://appleid.apple.com/auth/keys

JWT::decode($payload, JWK::parseKeySet($jwks), $supportedAlgorithm); // JWK::parseKeySet($jwks) returns an array having keys from **kid** value from each array item. You can either set array of keys or any specific one.
```

**Comment by bshaffer** [comment]
@ssi-anik added to README in https://github.com/firebase/php-jwt/pull/307

**Comment by bshaffer** [comment]
Parsing EC256 JWKs is now available as a development branch. Please see https://github.com/firebase/php-jwt/pull/399 if you'd like to try it out.
