### ISSUE TITLE
Class ExpiredException not found

### ISSUE THREAD

**Issue by rutwick** [firebase/php-jwt#71]
I have been trying to fix this since quite a while now. After my token expires, I get this exception:

PHP Fatal error:  Class 'ExpiredException' not found in C:\wamp...\php-jwt-master\src\JWT.php on line 119.

I tried adding the use statement to explicitly use the ExpiredException class, but it still gives me this error. I am trying to redirect the user by comparing the exp claim against the current time.

**Comment by psignoret** [comment]
Have you included `ExpiredException.php` (which defines the `ExpiredException` class)?

**Comment by sadranyi** [comment]
sorry but am new to jwt, i get the same issue, i have the "ExpiredException" class but its empty, do i need to write an implementation for this ? this seems to be the case for all the other ...Exception.php files included

**Comment by BondITSolutions** [comment]
@sadranyi You do not need to write an implementation for this, but if you want you could. Do note that it extends the `UnexpectedValueException` class, so it's not required at all. 

The error @rutwick is reporting hasn't anything to do with an 'empty class' either. PHP simply can't find the class at all. Make sure `ExpiredException.php` is included.

**Comment by xerardoo** [comment]
hi I'm newby in php, who knows how ignore exceptions from php-jwt , I want to handle errors

**Comment by alager** [comment]
Can anyone point out how to include this, if it's in the spl_autoload path already?  I'm confused...

` PHP Fatal error:  spl_autoload(): Class Firebase\JWT\ExpiredException could not be loaded in /usr/local/lib/JWT/JWT.php on line 119`

**Comment by bshaffer** [comment]
As mentioined, this is an autoload error. The solution is to properly install this package with composer (and include `vendor/autoload.php` in this script, as documented in this package's README, or provide your own solution for loading the class files (NOT RECOMMENDED).
