### ISSUE TITLE
Which version of spec does this conform to?

### ISSUE THREAD

**Issue by psignoret** [firebase/php-jwt#72]
This is probably just a doc bug--

README says that this "conforms to the current spec", but the link is to the [draft-ietf-oauth-json-web-token-06](https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-06), not the current [RFC 7519](https://tools.ietf.org/html/rfc7519).

**Comment by robertdimarco** [comment]
Good note! Updated the README.
