### ISSUE TITLE
Cannot handle token prior to ...

### ISSUE THREAD

**Issue by Adagal** [firebase/php-jwt#73]
I am getting this error on trying to validate a token. I explain:

1 - My AngularJS sends a http with credentials, database validates it and generates a token.
2 - AngularJS app stores the JWT token locally.
3 - On navigation the app sends the token to the server for validating expire data.
4 - Server throws this exception on trying to decode the JWT token received.

#0 C:\Server\www\routes\remember.php(17): Firebase\JWT\JWT::decode('eyJ0eXAiOiJKV1Q...', 'QWRhZ2FsIFNpc3R...', Array)
#1 [internal function]: Closure->{closure}(Object(Bullet\Request))
#2 C:\Server\www\vendor\vlucas\bulletphp\src\Bullet\App.php(311): call_user_func(Object(Closure), Object(Bullet\Request))
#3 C:\Server\www\vendor\vlucas\bulletphp\src\Bullet\App.php(195): Bullet\App->_runPath('GET', 'eyJ0eXAiOiJKV1Q...')
#4 C:\Server\www\index.php(39): Bullet\App->run(Object(Bullet\Request))
#5 {main}

**Comment by robertdimarco** [comment]
Please follow-up if you can find a minimal case that reproduces your issue with a valid token. The trace shown above, however, only suggests that the token is invalid.

**Comment by SimonEast** [comment]
I'm also getting this exception message in *some* circumstances when used from within the [Auth0 authentication library](https://github.com/auth0/auth0-PHP).  

    Cannot handle token prior to 2016-01-15T14:44:28+1100

It appears to happen when the server's clock is a few seconds behind the remote authentication server's. Is that a bug in the PHP-JWT library that it requires such strict time synchronization or should the remote server be returning an earlier timestamp?
