### ISSUE TITLE
why altering verify signature validation can be ok?

### ISSUE THREAD

**Issue by abioneperhobby** [firebase/php-jwt#74]
Hi
try this token

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vd3d3Lmdvb2dsZS5pdCIsImF1ZCI6Imh0dHA6Ly93d3cuZ29vZ2xlLml0IiwidXNlcm5hbWUiOiJhbmRyZWEuYmlzZWxsbyIsInJvbGVzIjpbImNhbkNyZWF0ZUNvbnRlbnQiLCJjYW5EZWxldGVDb250ZW50Il19.JQ_lBPw-YKYWeHGstnKSyOOkAwo3EJMQUTr328YW5ic

and verify with this key 9FFF4CB4B9B23C671D327AA84C2F9

here http://jwt.io/

and everything is good.

but why altering the verify signature this still correct?

for example altering the last "c" with a "d", you will obtain a corret signature. how it is possible?

thanks

**Comment by robertdimarco** [comment]
Since the signature is Base64-encoded, it is possible that the last character includes some padding of some kind or the bits after the termination of the bytes are not used. You shouldn't find this behavior anywhere else besides the last character, though.

**Comment by soulseekah** [comment]
When altering the key and payload on jwt.io the signature is recalculated and replaced. Do not interact with that right part, it's not for validation, it's for constructing valid JWTs.
