### ISSUE TITLE
Verify Rs512 signature with a Public RSA key

### ISSUE THREAD

**Issue by brantstaven** [firebase/php-jwt#78]
I would like to be able to verify a RS512 / sha512 signature with an RSA PUBLIC KEY.  Do you have any plans to support that or is there some way to do it now.  Thanks.

**Comment by Dmatafonov** [comment]
+1

**Comment by tejuprasad** [comment]
+2!

**Comment by Shkeats** [comment]
@doapp-brant @Dmatafonov @tejuprasad As I understand it you can, see my reply on https://github.com/firebase/php-jwt/issues/100

**Comment by joostfaassen** [comment]
I've submitted PR #117 to support this.

**Comment by ajupazhamayil** [comment]
Closing this issue as RS512 is supported now.
