### ISSUE TITLE
Error on decoding jwt

### ISSUE THREAD

**Issue by Remeic** [firebase/php-jwt#80]
Hello guys , i'm  trying this library and i copy the code on the wiki but when i try to decode the jwt php report me an error.
Type: UnexpectedValueException
Message: Invalid claims encoding

i use slim php framework
you can see the error here http://piller.pillsoft.com/api/1/jwt

**Comment by ajmalmsali** [comment]
You missed the algo?
like, Firebase\JWT\JWT::decode('eyJ0eXAiOiJKV1Q...', 'example_key', array('HS256')) ??

**Comment by Remeic** [comment]
@ajmalmsali i set , see this http://pastebin.com/7n4B42nW
and sorry for delay i have to study for exams

**Comment by tuupola** [comment]
$keo !== $key

**Comment by Remeic** [comment]
@tuupola don't solve the issue but i move the token inside the function and now works, thanks again
