### ISSUE TITLE
Update latest release tag.

### ISSUE THREAD

**Issue by vtsao** [firebase/php-jwt#86]
The releases page doesn't have the latest release marked as "latest", this should be updated, otherwise GitHub collapses newer releases and hides them and it's confusing:
https://github.com/firebase/php-jwt/releases

**Comment by tacone** [comment]
According to readme.md and also https://jwt.io/ the only release showing is affected by a serious security issue, while all the hidden ones should be safe.

You could not make it up

**Comment by bshaffer** [comment]
This has been fixed!
