### ISSUE TITLE
JWT Token data visible when base64 decoding the token

### ISSUE THREAD

**Issue by samirsyed29** [firebase/php-jwt#97]
When I encode an array using a private key using JWT::encode($array, $privatekey). I get the encrypted token.

But when I base64_decode that token, the token is totally visible.

For example, below is the token the class generated : 

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJVc2VySUQiOiIyZGJhMjg1NC0wZGI0LTdhMDEtODMxNS05YWExNzA5MzQzZWUiLCJ0b2tlbl9leHBpcnkiOjE0NjU5Mzk3NzcsInNlY3JldF9pbmZvIjoibXlfc2VydmVyc19zZWNyZXRfaW5mbyJ9.36a0iYzdcgpyxAQjpqnD3kUUaoUjldDcfcjCKkCHhCk

Now, if someone just gets the token somehow, and just base64 decodes it, they can see the whole info inside the token.

Go ahead and base64 decode it and see for your self.

Please let me know if I need to know something or if Im doing something wrong with the encoding part.

**Comment by tuupola** [comment]
Yes, this is how JWT works. It is not encrypted. It is signed. If somebody alters the content of the token validation will fail because signature does not match any more.

https://jwt.io/introduction/

**Comment by dperjar** [comment]
Beat me to it... but don't put anything confidential in the JWT payload.

**Comment by samirsyed29** [comment]
So basically, anyone except that person can have access to protected resources with the token he/she has. If he/she alters it, they won't have access to other users resources other than their own.

And thank you for letting me know to not put confidential info in the token.

**Comment by maltboy** [comment]
Is there a better way now? Such as encryption
