### ISSUE TITLE
"Unknown JSON error"

### ISSUE THREAD

**Issue by baschny** [firebase/php-jwt#99]
I get lots of "Unknown JSON error: 5". Why not handle all the potential PHP json decoding errors in `handleJsonError` and display the real error instead? Only 1,2,3 seem to be handled currently, while others were added in newer PHP versions.

See potential errors here: http://php.net/manual/en/function.json-last-error.php

Or use http://php.net/manual/en/function.json-last-error-msg.php (for PHP >5.5).

**Comment by bshaffer** [comment]
fixed in #110
